"""Fibonacci numbers: iterative, recursive, and full series.

Generated by JARVIS Coding Brain Pro for: write python code for fibonacci in fib_ult_test.py"""
from typing import List


def fib_iterative(n: int) -> int:
    """Return the n-th Fibonacci number (0-indexed) iteratively."""
    if n < 0:
        raise ValueError("n must be >= 0")
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def fib_recursive(n: int) -> int:
    """Return the n-th Fibonacci number recursively."""
    if n < 0:
        raise ValueError("n must be >= 0")
    if n < 2:
        return n
    return fib_recursive(n - 1) + fib_recursive(n - 2)


def fib_series(count: int) -> List[int]:
    """Return the first *count* Fibonacci numbers."""
    series: List[int] = []
    a, b = 0, 1
    for _ in range(max(0, count)):
        series.append(a)
        a, b = b, a + b
    return series


if __name__ == "__main__":
    print("iterative fib(10):", fib_iterative(10))
    print("recursive fib(10):", fib_recursive(10))
    print("series:", fib_series(10))

