#!/usr/bin/env python3
"""Batch 3: generate 500+ knowledge skills and inject into brain_extra.py
right before the OFFLINE CHAT ENGINE marker."""
import json
import os
import re
import sys

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "brain_extra.py")
MARKER = "# OFFLINE CHAT ENGINE"
BATCH_TAG = "# -- AUTO-GENERATED KNOWLEDGE SKILLS (batch 3, gen_skills3.py) --"

# ---------------------------------------------------------------- science ---
science = [
    ("why is the sky blue", "Sunlight scatters off air molecules, and blue light scatters the most because it travels in shorter waves. That scattered blue is what fills the sky, sir."),
    ("why is mars red", "Mars is covered in iron oxide, essentially rust, which gives it its distinctive reddish color, sir."),
    ("how do vaccines work", "Vaccines train your immune system by showing it a harmless piece of a pathogen so it can build defenses before meeting the real thing, sir."),
    ("why do we dream", "Scientists believe dreaming helps the brain process emotions, consolidate memories, and rehearse responses to threats, sir."),
    ("what causes thunder", "Thunder is the sound of air rapidly expanding around a lightning bolt as it superheats to roughly 30,000 degrees Celsius, sir."),
    ("what is lightning", "Lightning is a giant electrostatic discharge between clouds or between a cloud and the ground, several times hotter than the sun's surface, sir."),
    ("how do rainbows form", "Rainbows form when sunlight refracts inside water droplets, splitting into the spectrum of colors we see arcing across the sky, sir."),
    ("why do leaves change color in autumn", "As days shorten, chlorophyll breaks down and reveals yellow and orange pigments, while some trees produce red anthocyanins, sir."),
    ("how do chameleons change color", "Chameleons adjust tiny crystals in their skin cells that reflect different wavelengths of light, changing their color, sir."),
    ("how do magnets work", "Magnetism arises from the alignment of electron spins in a material, creating a field that attracts or repels certain metals, sir."),
    ("why does ice float", "Ice floats because water expands as it freezes, making frozen water about nine percent less dense than liquid water, sir."),
    ("what makes the sun shine", "The sun shines through nuclear fusion, converting about 600 million tons of hydrogen into helium every second and releasing enormous energy, sir."),
    ("how far is the sun from earth", "The sun is about 150 million kilometers away, and its light takes roughly eight minutes and twenty seconds to reach us, sir."),
    ("what is a light year", "A light year is the distance light travels in one year, about 9.46 trillion kilometers, sir."),
    ("how many bones are in the human body", "Adults have 206 bones; babies are born with around 300 which fuse together as they grow, sir."),
    ("why do we yawn", "Yawning may help cool the brain and increase alertness, and it is contagious because of social mirroring, sir."),
    ("why do we sneeze", "Sneezing is a reflex that expels irritants like dust, pollen, or germs from your nasal passages at high speed, sir."),
    ("what is blood made of", "Blood is about 55 percent plasma plus red cells that carry oxygen, white cells that fight infection, and platelets that clot wounds, sir."),
    ("how does the heart work", "The heart is a muscle that contracts about 100,000 times a day, pumping roughly 7,500 liters of blood through your body, sir."),
    ("what causes hiccups", "Hiccups happen when your diaphragm spasms involuntarily and your vocal cords snap shut, producing the characteristic hic sound, sir."),
    ("how big is the universe", "The observable universe spans about 93 billion light years across, and the whole universe may be far larger still, sir."),
    ("what is the milky way", "The Milky Way is our barred spiral galaxy, home to somewhere between 100 and 400 billion stars including our sun, sir."),
    ("what is a comet", "A comet is a ball of ice, dust, and rock that grows a glowing tail when it approaches the sun and heats up, sir."),
    ("what is an asteroid", "An asteroid is a rocky body orbiting the sun, mostly found in the belt between Mars and Jupiter, sir."),
    ("difference between meteor and meteorite", "A meteor is the streak of light as space rock burns in our atmosphere; if it survives and lands, it is called a meteorite, sir."),
    ("what is the northern lights", "The aurora occurs when charged solar particles strike gases in the upper atmosphere near the poles, painting green and red curtains of light, sir."),
    ("what is a solar eclipse", "A solar eclipse happens when the moon passes directly between Earth and the sun, casting its shadow on us, sir."),
    ("what is a lunar eclipse", "A lunar eclipse happens when Earth passes between the sun and moon, casting a shadow that turns the moon coppery red, sir."),
    ("why does the moon change shape", "The moon's phases come from changing angles between the sun, Earth, and moon across a cycle of about 29.5 days, sir."),
    ("what is a nebula", "A nebula is an enormous cloud of gas and dust in space, often the birthplace of new stars, sir."),
    ("what is a pulsar", "A pulsar is a spinning neutron star that beams radiation like a lighthouse as it rotates, some hundreds of times per second, sir."),
    ("what is a quasar", "A quasar is an extremely bright galactic core powered by matter falling into a supermassive black hole, visible across billions of light years, sir."),
    ("what is antimatter", "Antimatter is matter with opposite charge; when it meets normal matter both annihilate into pure energy, sir."),
    ("what is a molecule", "A molecule is two or more atoms bonded together, like H2O, the water molecule made of two hydrogens and one oxygen, sir."),
    ("states of matter", "There are four common states: solid, liquid, gas, and plasma, each defined by how tightly particles are bound together, sir."),
    ("what is plasma state", "Plasma is ionized gas where electrons break free from atoms; it makes up over 99 percent of the visible universe, sir."),
    ("what is surface tension", "Surface tension comes from water molecules clinging together at the surface, strong enough to let insects walk on water, sir."),
    ("what is capillary action", "Capillary action is how liquids climb narrow spaces against gravity, the way water rises through a paper towel, sir."),
    ("how do batteries work", "Batteries convert stored chemical energy into electricity through reactions between electrodes, pushing electrons through your circuit, sir."),
    ("how do lasers work", "Lasers amplify light by stimulating atoms to emit photons in perfect step, producing a tight, single-color beam, sir."),
    ("what is static electricity", "Static electricity builds when electrons transfer between surfaces through friction, then discharge with a spark, sir."),
    ("what is the doppler effect", "The Doppler effect is why a siren sounds higher approaching you and lower moving away: motion shifts wave frequency, sir."),
    ("why do stars twinkle", "Stars twinkle because their light bends as it passes through shifting layers of turbulent air in our atmosphere, sir."),
    ("why is the ocean salty", "Rivers dissolve minerals from rocks over millions of years and carry them seaward, leaving the ocean about 3.5 percent salt, sir."),
    ("what causes ocean tides", "Tides are caused mainly by the moon's gravitational pull dragging Earth's oceans into bulges on opposite sides of the planet, sir."),
    ("how do clouds form", "Clouds form when warm moist air rises, cools, and water vapor condenses onto tiny airborne particles, sir."),
    ("what causes earthquakes", "Earthquakes occur when stress along tectonic plate boundaries releases suddenly, sending shockwaves through the ground, sir."),
    ("what is a volcano", "A volcano is an opening in Earth's crust where molten magma, ash, and gas erupt from below the surface, sir."),
    ("what was pangaea", "Pangaea was the supercontinent that assembled most landmasses about 335 million years ago before breaking into today's continents, sir."),
    ("how old is planet earth", "Earth formed about 4.5 billion years ago from the disk of debris surrounding the young sun, sir."),
    ("what is the water cycle", "Water evaporates from oceans, condenses into clouds, falls as precipitation, and flows back to the sea in a continuous loop, sir."),
    ("what is plate tectonics", "Plate tectonics describes Earth's crust as drifting plates whose collisions and separations build mountains and open oceans, sir."),
    ("why does bread rise", "Yeast ferments sugars releasing carbon dioxide, and gluten traps the bubbles, making dough puff up as it bakes, sir."),
    ("how does soap clean", "Soap molecules have one end that binds to grease and one end that loves water, letting dirt be rinsed away, sir."),
    ("why does metal feel colder than wood", "Metal conducts heat away from your hand faster than wood, so it feels colder even at the same temperature, sir."),
]

# ---------------------------------------------------------------- history ---
history = [
    ("who was cleopatra", "Cleopatra VII was the last active ruler of ancient Egypt, famous for her intelligence, alliances with Rome, and dramatic end in 30 BC, sir."),
    ("who was julius caesar", "Julius Caesar was a Roman general who conquered Gaul and became dictator before being assassinated on the Ides of March in 44 BC, sir."),
    ("who was alexander the great", "Alexander the Great built one of history's largest empires by age 30, stretching from Greece to India before dying at 32 in 323 BC, sir."),
    ("who was genghis khan", "Genghis Khan united the Mongol tribes and founded the largest contiguous land empire in history during the 13th century, sir."),
    ("who was joan of arc", "Joan of Arc was a French peasant girl who led armies to victory at 17 and became a national heroine and Catholic saint, sir."),
    ("who was napoleon bonaparte", "Napoleon Bonaparte rose from artillery officer to Emperor of France, conquering much of Europe before his final defeat at Waterloo in 1815, sir."),
    ("who was queen victoria", "Queen Victoria ruled Britain for 63 years from 1837 to 1901, an era of industrial expansion known as the Victorian age, sir."),
    ("who was george washington", "George Washington led the American Revolution to victory and became the first US president in 1789, sir."),
    ("who was thomas jefferson", "Thomas Jefferson authored the Declaration of Independence and served as the third US president, sir."),
    ("who was michelangelo", "Michelangelo painted the Sistine Chapel ceiling and sculpted David, standing among the greatest artists of the Renaissance, sir."),
    ("who was galileo galilei", "Galileo pioneered observational astronomy, discovering Jupiter's moons and defending the idea that Earth orbits the sun, sir."),
    ("who was louis pasteur", "Louis Pasteur proved germ theory, invented pasteurization, and developed early vaccines for rabies and anthrax, sir."),
    ("who was florence nightingale", "Florence Nightingale revolutionized nursing and hospital sanitation during the Crimean War, founding modern nursing practice, sir."),
    ("who was harriet tubman", "Harriet Tubman escaped slavery and repeatedly risked her life guiding dozens of others to freedom on the Underground Railroad, sir."),
    ("who was walt disney", "Walt Disney created Mickey Mouse, pioneered feature animation, and built Disneyland, transforming family entertainment, sir."),
    ("who built the great wall of china", "Chinese dynasties began the Great Wall over 2,000 years ago, with most surviving sections built during the Ming dynasty, sir."),
    ("when did the roman empire fall", "The Western Roman Empire fell in 476 AD when the last emperor was deposed; the Eastern half endured nearly another thousand years, sir."),
    ("when did world war 1 begin", "World War I began in July 1914 after the assassination of Archduke Franz Ferdinand in Sarajevo, sir."),
    ("when did world war 2 end", "World War II ended in 1945: Germany surrendered in May and Japan formally surrendered in September, sir."),
    ("when did the vietnam war end", "American combat troops withdrew in 1973, and Saigon fell in April 1975, reuniting Vietnam under the north, sir."),
    ("when was the korean war", "The Korean War raged from 1950 to 1953, ending in an armistice rather than a formal peace treaty, sir."),
    ("when did india become independent", "India won independence from British rule on August 15, 1947, becoming the world's largest democracy, sir."),
    ("when did the titanic sink", "The Titanic struck an iceberg on the night of April 14, 1912, and sank early on April 15 with heavy loss of life, sir."),
    ("where were the first modern olympics held", "Athens, Greece hosted the first modern Olympic Games in 1896, reviving a tradition from ancient Greece, sir."),
    ("who built the pyramids of giza", "Egyptian workers, not slaves, built the Giza pyramids around 4,500 years ago as tombs for the pharaohs, sir."),
    ("what was the silk road", "The Silk Road was an ancient trade network linking China with Central Asia, India, and Europe, carrying goods, ideas, and inventions, sir."),
    ("what was the black death plague", "The Black Death swept Europe from 1347 to 1351, killing an estimated one-third of the population, sir."),
    ("what was the spanish flu", "The Spanish flu pandemic of 1918 to 1920 infected roughly a third of humanity and killed tens of millions worldwide, sir."),
    ("when did american women get the vote", "American women won the right to vote nationwide in 1920 with the ratification of the 19th Amendment, sir."),
    ("when did slavery end in america", "Slavery was abolished in the United States in 1865 through the 13th Amendment after the Civil War, sir."),
    ("what was the boston tea party", "The Boston Tea Party of 1773 saw American colonists dump British tea into the harbor in protest against taxation, sir."),
    ("what was the french revolution about", "The French Revolution of 1789 overthrew the monarchy in the name of liberty, equality, and fraternity, reshaping modern politics, sir."),
    ("who were the vikings", "The Vikings were Scandinavian seafarers who raided, traded, and settled across Europe and reached North America centuries before Columbus, sir."),
    ("what was the aztec empire", "The Aztec Empire centered on Tenochtitlan in today's Mexico City flourished until Spanish conquistadors toppled it in 1521, sir."),
    ("what was the mongol empire", "The Mongol Empire became the largest contiguous empire ever, spanning Asia into Europe and reviving trade along the Silk Road, sir."),
    ("who was the first man on the moon", "Neil Armstrong stepped onto the lunar surface on July 20, 1969, followed minutes later by Buzz Aldrin, sir."),
    ("who was the first woman in space", "Soviet cosmonaut Valentina Tereshkova became the first woman in space aboard Vostok 6 in June 1963, sir."),
    ("what was the apollo program", "NASA's Apollo program ran from 1961 to 1972 and landed twelve astronauts on the moon across six successful missions, sir."),
    ("what was the manhattan project about", "The Manhattan Project was America's secret WWII program that developed the first atomic bombs under J. Robert Oppenheimer, sir."),
    ("when was the declaration of independence signed", "The Continental Congress adopted the Declaration of Independence on July 4, 1776, sir."),
    ("when was the constitution written", "The US Constitution was drafted in 1787 in Philadelphia and took effect in 1789 after ratification, sir."),
    ("who discovered america first", "Indigenous peoples arrived thousands of years ago; Norse explorer Leif Erikson landed around 1000 AD, and Columbus reached the Caribbean in 1492, sir."),
    ("when did the industrial revolution start", "The Industrial Revolution began in Britain around 1760, powered by steam engines, factories, and mechanized textile production, sir."),
    ("what started world war 1", "The assassination of Archduke Franz Ferdinand in June 1914 triggered alliances that pulled Europe into war within weeks, sir."),
    ("what ended world war 2 in europe", "Germany's unconditional surrender on May 8, 1945 marked Victory in Europe Day, ending WWII there, sir."),
    ("who was mahatma gandhi biography", "Gandhi trained as a lawyer in London, developed satyagraha nonviolence in South Africa, and led India to freedom in 1947, sir."),
    ("who was winston churchill biography", "Churchill served Britain as soldier, writer, and prime minister twice, most famously rallying the nation against Nazi Germany, sir."),
    ("who was abraham lincoln biography", "Lincoln was born in a log cabin in 1809, self-taught himself law, held the Union together, and pushed the 13th Amendment abolishing slavery, sir."),
    ("who was nelson mandela biography", "Mandela spent 27 years in prison for opposing apartheid, then emerged to negotiate democracy and serve as South Africa's first Black president, sir."),
    ("who was martin luther king jr biography", "Martin Luther King Jr. was a Baptist minister who led the civil rights movement and delivered his 'I Have a Dream' speech in 1963, sir."),
    ("when was the un founded", "The United Nations was founded on October 24, 1945, after World War II, to maintain international peace and cooperation, sir."),
    ("when did the cold war start", "Tensions hardened into the Cold War by 1947 as the US and Soviet Union emerged as rival superpowers, sir."),
    ("when did the soviet union collapse", "The Soviet Union dissolved in December 1991, ending decades of communist rule and the Cold War era, sir."),
    ("who was rani lakshmibai", "Rani Lakshmibai of Jhansi was a queen who fought British forces heroically during India's 1857 rebellion, becoming an enduring icon, sir."),
    ("who was bhagat singh", "Bhagat Singh was an Indian revolutionary who fought British colonial rule and became a martyr at just 23 in 1931, sir."),
    ("when was the taj mahal built", "Emperor Shah Jahan built the Taj Mahal between 1632 and 1653 as a marble mausoleum for his beloved wife Mumtaz Mahal, sir."),
]

# --------------------------------------------------------------- geography ---
geography = [
    ("capital of france", "Paris has been France's capital city for centuries, famed for the Eiffel Tower and the Louvre, sir."),
    ("capital of japan", "Tokyo is Japan's capital and one of the most populous metropolitan areas in the world, sir."),
    ("capital of australia", "Canberra is Australia's capital, purpose-built as a compromise between Sydney and Melbourne, sir."),
    ("capital of canada", "Ottawa is Canada's capital, sitting on the border of Ontario and Quebec, sir."),
    ("capital of brazil", "Brasilia is Brazil's planned capital city, inaugurated in 1960, sir."),
    ("capital of china", "Beijing is China's capital, home to the Forbidden City and Tiananmen Square, sir."),
    ("capital of russia", "Moscow is Russia's capital and largest city, centered on the Kremlin, sir."),
    ("capital of italy", "Rome is Italy's capital, once heart of the Roman Empire, sir."),
    ("capital of spain", "Madrid is Spain's capital and largest city, sitting almost exactly in the country's center, sir."),
    ("capital of germany", "Berlin is Germany's capital, famously divided until the Wall fell in 1989, sir."),
    ("capital of egypt", "Cairo is Egypt's sprawling capital on the Nile, near the pyramids of Giza, sir."),
    ("capital of argentina", "Buenos Aires is Argentina's capital, often called the Paris of South America, sir."),
    ("capital of mexico", "Mexico City is the capital, built atop the ruins of the Aztec capital Tenochtitlan, sir."),
    ("capital of thailand", "Bangkok is Thailand's capital, officially known by one of the longest place names on Earth, sir."),
    ("largest country by area", "Russia is the largest country on Earth, covering about 17 million square kilometers, eleven time zones wide, sir."),
    ("smallest ocean", "The Arctic Ocean is the smallest and shallowest ocean, capping the top of the globe, sir."),
    ("longest mountain range", "The Andes stretch about 7,000 kilometers along South America, the longest continental mountain range, sir."),
    ("highest mountain range", "The Himalayas hold the tallest peaks on Earth including Everest at 8,849 meters, sir."),
    ("tallest waterfall in the world", "Angel Falls in Venezuela plunges 979 meters, the highest uninterrupted waterfall anywhere, sir."),
    ("biggest island in the world", "Greenland is the largest island, covering about 2.16 million square kilometers, sir."),
    ("largest lake in the world", "The Caspian Sea is the largest enclosed inland body of water, shared by five countries, sir."),
    ("deepest lake in the world", "Lake Baikal in Siberia plunges about 1,642 meters and holds a fifth of the world's unfrozen fresh water, sir."),
    ("where is the amazon river", "The Amazon flows roughly 6,400 kilometers across Peru, Colombia, and Brazil, carrying more water than any other river, sir."),
    ("where are the himalayas", "The Himalayas arc across five countries: Nepal, India, Bhutan, China, and Pakistan, sir."),
    ("how tall is mount everest", "Mount Everest stands 8,849 meters above sea level, first summited by Hillary and Norgay in 1953, sir."),
    ("where is the dead sea", "The hyper-salty Dead Sea lies between Jordan and Israel, and at about 430 meters below sea level it is Earth's lowest land point, sir."),
    ("what is the great barrier reef", "The Great Barrier Reef off Queensland, Australia is the largest coral reef system on Earth, visible even from space, sir."),
    ("where is the eiffel tower", "The Eiffel Tower rises over Paris, France, built for the 1889 World's Fair, sir."),
    ("how tall is the eiffel tower", "The Eiffel Tower stands about 330 meters tall including antennas, and sways slightly with temperature, sir."),
    ("where is the statue of liberty", "Lady Liberty stands on Liberty Island in New York Harbor, a gift from France dedicated in 1886, sir."),
    ("where is the taj mahal located", "The Taj Mahal sits in Agra, India, on the banks of the Yamuna River, sir."),
    ("where is machu picchu", "Machu Picchu clings to an Andean ridge in Peru at about 2,430 meters elevation, built by the Inca in the 1400s, sir."),
    ("where is the colosseum", "The Colosseum stands in central Rome, Italy, completed around 80 AD as a gladiatorial arena, sir."),
    ("where is the great pyramid of giza", "The Great Pyramid rises on the Giza plateau near Cairo, Egypt, and is the last surviving Ancient Wonder, sir."),
    ("where is petra", "Petra is a rock-cut city carved by the Nabataeans in southern Jordan over 2,000 years ago, sir."),
    ("where is the grand canyon", "The Grand Canyon slices through northern Arizona, carved by the Colorado River over millions of years, sir."),
    ("where is victoria falls", "Victoria Falls thunders on the Zambia-Zimbabwe border; locals call it Mosi-oa-Tunya, the smoke that thunders, sir."),
    ("where is niagara falls", "Niagara Falls straddles the border between New York State and Ontario, Canada, sir."),
    ("how many continents are there", "There are seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia, sir."),
    ("how many oceans are there", "Five oceans are recognized today: Pacific, Atlantic, Indian, Southern, and Arctic, sir."),
    ("what is the equator", "The equator is the invisible line of zero latitude circling Earth's middle, where days and nights stay nearly equal, sir."),
    ("what is the prime meridian", "The Prime Meridian marks zero longitude, running through Greenwich, England since 1884, sir."),
    ("largest continent", "Asia is the largest continent, holding about 60 percent of the world's population, sir."),
    ("what is the danube river", "The Danube is Europe's second-longest river, flowing through or alongside ten countries and four capitals, sir."),
    ("what is lake titicaca", "Lake Titicaca sits high in the Andes between Peru and Bolivia, the highest navigable large lake in the world, sir."),
    ("what is the arctic circle", "The Arctic Circle is the latitude at 66.5 degrees north, north of which the summer sun never sets, sir."),
    ("what is the ring of fire", "The Ring of Fire is a horseshoe of volcanoes and quake-prone faults ringing the Pacific, hosting about three-quarters of Earth's volcanoes, sir."),
    ("what is the bermuda triangle", "The Bermuda Triangle is a legendary region of the North Atlantic where ships and planes were rumored to vanish; statistics show nothing unusual, sir."),
    ("driest place on earth", "Chile's Atacama Desert can go years without meaningful rain, the driest non-polar place on Earth, sir."),
    ("wettest place on earth", "Mawsynram in Meghalaya, India records the highest average annual rainfall, drenched by monsoon skies, sir."),
    ("coldest place on earth", "Vostok Station in Antarctica recorded minus 89.2 degrees Celsius in 1983, the coldest temperature ever measured, sir."),
    ("hottest place on earth", "Death Valley, California hit 56.7 degrees Celsius in 1913, still the hottest reliably recorded temperature, sir."),
    ("how many time zones in the world", "Theoretically 24, one per hour, but real-world offsets create nearly 40 distinct time zones, sir."),
    ("describe the flag of japan", "Japan's flag is a crimson disc representing the sun, centered on a plain white field, sir."),
    ("describe the flag of canada", "Canada's flag shows a red maple leaf flanked by red bars on white, adopted in 1965, sir."),
    ("describe the flag of brazil", "Brazil's flag features a green field, yellow diamond, and blue globe with stars and the motto Ordem e Progresso, sir."),
    ("describe the flag of india", "India's tricolor runs saffron, white, and green with the navy Ashoka Chakra wheel at center, sir."),
    ("describe the flag of switzerland", "Switzerland's flag is a bold white cross on red, one of only two square national flags, sir."),
    ("which country has the most islands", "Sweden tops the list with roughly 267,000 islands, though most are uninhabited, sir."),
    ("what is the sahara desert", "The Sahara is the world's largest hot desert, sweeping 9 million square kilometers across North Africa, sir."),
]

# -------------------------------------------------------------- technology ---
technology = [
    ("who invented the computer", "Charles Babbage designed the mechanical Analytical Engine in the 1830s and is honored as the father of the computer, sir."),
    ("who invented the internet", "No single inventor: ARPANET connected the first nodes in 1969, built by teams funded by the US Department of Defense, sir."),
    ("who invented the telephone", "Alexander Graham Bell received the first telephone patent in 1876, sir."),
    ("who invented television", "John Logie Baird demonstrated early mechanical TV in 1926, while Philo Farnsworth's electronic design followed in 1927, sir."),
    ("who invented email", "Ray Tomlinson sent the first network email to himself in 1971 and chose the @ symbol for addresses, sir."),
    ("who invented the computer mouse", "Douglas Engelbart invented the mouse in the 1960s while exploring human-computer interaction, sir."),
    ("first programming language", "Konrad Zuse designed Plankalkul in the 1940s, but Fortran, released in 1957, was the first widely used high-level language, sir."),
    ("what was the first computer virus", "Creeper, written in 1971, hopped between ARPANET machines displaying 'I'm the creeper, catch me if you can', sir."),
    ("when was the first video game made", "Physicist William Higinbotham built Tennis for Two in 1958, while Pong brought video games to the public in 1972, sir."),
    ("when was the first iphone released", "Steve Jobs unveiled the iPhone in January 2007 and it went on sale that June, sir."),
    ("when was google founded", "Larry Page and Sergey Brin founded Google in September 1998 while PhD students at Stanford, sir."),
    ("when was facebook founded", "Mark Zuckerberg launched Facebook from his Harvard dorm room in February 2004, sir."),
    ("when was amazon founded", "Jeff Bezos started Amazon in 1994 as an online bookstore operating out of his garage, sir."),
    ("when was microsoft founded", "Bill Gates and Paul Allen founded Microsoft in April 1975 to write software for the Altair, sir."),
    ("when was apple founded", "Steve Jobs, Steve Wozniak, and Ronald Wayne founded Apple on April 1, 1976, in a garage, sir."),
    ("when was tesla founded", "Tesla Motors was founded in 2003 by Martin Eberhard and Marc Tarpenning; Elon Musk joined early as an investor and later CEO, sir."),
    ("when was openai founded", "OpenAI was founded in December 2015 by Sam Altman, Elon Musk, Greg Brockman, and other researchers, sir."),
    ("who founded google", "Larry Page and Sergey Brin founded Google in 1998, building on their BackRub search research, sir."),
    ("who founded microsoft", "Childhood friends Bill Gates and Paul Allen founded Microsoft in 1975, sir."),
    ("who founded apple", "Steve Jobs and Steve Wozniak co-founded Apple in 1976 with Ronald Wayne, sir."),
    ("who founded facebook", "Mark Zuckerberg co-founded Facebook in 2004 with classmates Saverin, Hughes, Moskovitz, and the Winklevoss twins, sir."),
    ("what does cpu stand for", "CPU means Central Processing Unit, the chip that executes your computer's instructions, sir."),
    ("what does gpu stand for", "GPU means Graphics Processing Unit, specialized hardware for rendering images and parallel computing, sir."),
    ("what does ram stand for", "RAM means Random Access Memory, your computer's fast temporary workspace, sir."),
    ("what does ssd stand for", "SSD means Solid-State Drive, storage with no moving parts that is far faster than old hard disks, sir."),
    ("what does url stand for", "URL means Uniform Resource Locator, the address your browser uses to find a page, sir."),
    ("what does html stand for", "HTML means HyperText Markup Language, the standard structure behind every web page, sir."),
    ("what does http stand for", "HTTP means HyperText Transfer Protocol, the rules browsers use to fetch web pages, sir."),
    ("what does usb stand for", "USB means Universal Serial Bus, the standard port connecting peripherals to computers, sir."),
    ("what does led stand for", "LED means Light-Emitting Diode, an efficient semiconductor light source, sir."),
    ("what does pdf stand for", "PDF means Portable Document Format, created by Adobe in 1993 to preserve layout everywhere, sir."),
    ("what does wifi stand for", "Wi-Fi does not technically stand for anything; it is a brand name playing on hi-fi for wireless networking, sir."),
    ("what does npc stand for", "NPC means Non-Player Character, any game character not controlled by a human, sir."),
    ("what does rpg stand for", "In gaming RPG means Role-Playing Game, where players develop characters over long adventures, sir."),
    ("what does fps mean in games", "FPS can mean First-Person Shooter genre or Frames Per Second performance measure, depending on context, sir."),
    ("what is a gigabyte", "A gigabyte is about one billion bytes, enough to store roughly 250 songs or a few hundred photos, sir."),
    ("difference between ram and rom", "RAM is fast working memory wiped when power cuts; ROM permanently stores startup instructions that survive shutdowns, sir."),
    ("difference between hardware and software", "Hardware is the physical machinery you can touch; software is the code and programs telling it what to do, sir."),
    ("what is an operating system", "The operating system manages hardware and apps; Windows, macOS, Linux, Android, and iOS are examples, sir."),
    ("what is a web browser", "A browser fetches and renders websites; Chrome, Safari, Firefox, and Edge are popular ones, sir."),
    ("what is bluetooth technology", "Bluetooth provides short-range wireless connections between devices, named after a 10th-century Danish king, sir."),
    ("what is 5g network", "5G is the fifth generation of cellular networks, delivering faster speeds and lower latency than 4G, sir."),
    ("what does lte stand for", "LTE means Long-Term Evolution, the technical standard behind most 4G mobile networks, sir."),
    ("what is nfc", "NFC means Near-Field Communication, the tap-to-pay chip technology in phones and cards, sir."),
    ("what is gps and how does it work", "GPS receivers listen to signals from orbiting satellites and triangulate timing differences to pinpoint your location, sir."),
    ("what is a qr code", "A QR code is a square barcode storing data readable by cameras, invented by Denso Wave in Japan in 1994, sir."),
    ("how does facial recognition work", "Facial recognition maps distances between facial landmarks into a mathematical signature for matching, sir."),
    ("what is voice recognition", "Voice recognition converts spoken words into text or commands using acoustic and language models, sir."),
    ("what is chatgpt", "ChatGPT is OpenAI's conversational AI chatbot launched in November 2022, built on the GPT language model family, sir."),
    ("what is firmware", "Firmware is low-level software baked into hardware that controls how the device boots and behaves, sir."),
    ("what is a device driver", "A driver is software that lets the operating system communicate with specific hardware like printers or GPUs, sir."),
    ("what is a kernel", "The kernel is the core of an operating system, managing memory, processes, and hardware access, sir."),
    ("what is an emulator", "An emulator mimics one computing system inside another, letting old consoles run on modern machines, sir."),
    ("what is overclocking", "Overclocking pushes a processor above its rated speed for extra performance at the cost of heat and stability, sir."),
    ("what is two factor authentication", "Two-factor authentication adds a second proof of identity, usually a code sent to your phone, beyond your password, sir."),
    ("what is end to end encryption", "End-to-end encryption scrambles messages so only sender and receiver can read them; not even the service provider can, sir."),
    ("what are internet cookies", "Cookies are small files sites store on your browser to remember logins, carts, preferences, and tracking data, sir."),
    ("what is ransomware", "Ransomware is malware that encrypts victims' files and demands payment for the unlock key, sir."),
    ("what is spyware", "Spyware secretly installs itself to monitor activity and harvest personal data without consent, sir."),
    ("what is a smart contract", "A smart contract is self-executing code on a blockchain that runs automatically when conditions are met, sir."),
    ("what is edge computing", "Edge computing processes data near where it is generated instead of sending everything to distant cloud servers, sir."),
]

# ----------------------------------------------------------- entertainment ---
entertainment = [
    ("who directed jurassic park", "Steven Spielberg directed Jurassic Park, released in 1993 with groundbreaking dinosaur effects, sir."),
    ("who directed inception", "Christopher Nolan wrote and directed Inception, the 2010 dreams-within-dreams thriller, sir."),
    ("who directed titanic movie", "James Cameron directed Titanic, which swept the 1998 Oscars with eleven wins, sir."),
    ("who directed avatar movie", "James Cameron directed Avatar, pioneering 3D motion capture when it premiered in 2009, sir."),
    ("who directed the godfather", "Francis Ford Coppola adapted The Godfather to screen in 1972, widely considered cinema's greatest film, sir."),
    ("who directed star wars", "George Lucas wrote and directed the original Star Wars in 1977, sir."),
    ("who directed pulp fiction", "Quentin Tarantino directed Pulp Fiction in 1994, winning the Palme d'Or and an original screenplay Oscar, sir."),
    ("what was the first movie ever made", "Louis Le Prince's Roundhay Garden Scene from 1888 is considered the earliest surviving film, barely two seconds long, sir."),
    ("highest grossing movie of all time", "Avatar holds the global box office crown with nearly 3 billion dollars including its re-releases, sir."),
    ("which movie won the most oscars", "Ben-Hur, Titanic, and The Lord of the Rings: The Return of the King share the record with eleven Academy Awards each, sir."),
    ("who has won the most oscars ever", "Walt Disney personally won 22 competitive Academy Awards, the record for any individual, sir."),
    ("why is it called an oscar", "Academy Awards got the nickname Oscar reportedly from a librarian who said the statuette resembled her Uncle Oscar, sir."),
    ("who created mickey mouse", "Walt Disney and animator Ub Iwerks created Mickey Mouse, who debuted in Steamboat Willie in 1928, sir."),
    ("what was disney's first animated movie", "Snow White and the Seven Dwarfs in 1937 was Disney's and Hollywood's first full-length animated feature, sir."),
    ("how many harry potter movies are there", "Eight films adapt the seven Harry Potter books, with the final novel split into two parts, sir."),
    ("who wrote harry potter books", "J.K. Rowling wrote the seven Harry Potter novels between 1997 and 2007, sir."),
    ("who is called the king of pop", "Michael Jackson earned the title King of Pop with albums like Thriller, the best-selling album ever, sir."),
    ("who is called the queen of pop", "Madonna is widely dubbed the Queen of Pop for decades of chart-topping reinvention, sir."),
    ("who were the beatles members", "John Lennon, Paul McCartney, George Harrison, and Ringo Starr formed the Beatles out of Liverpool in 1960, sir."),
    ("who wrote the song imagine", "John Lennon wrote Imagine, released in 1971 as a solo artist after the Beatles split, sir."),
    ("how many symphonies did beethoven write", "Beethoven completed nine symphonies, composing the Ninth while completely deaf, sir."),
    ("what is a grammy award", "The Grammy honors musical excellence each year, presented by the Recording Academy since 1959, sir."),
    ("who wrote the book 1984", "George Orwell published Nineteen Eighty-Four in 1949, warning of surveillance and totalitarianism, sir."),
    ("who wrote pride and prejudice", "Jane Austen wrote Pride and Prejudice, published in 1813, sir."),
    ("who wrote moby dick", "Herman Melville wrote Moby-Dick, the tale of Captain Ahab's obsession with the white whale, sir."),
    ("who wrote war and peace", "Leo Tolstoy wrote War and Peace, the epic of Napoleonic-era Russia, sir."),
    ("who wrote oliver twist", "Charles Dickens wrote Oliver Twist, serialised in 1837, sir."),
    ("who wrote hamlet", "William Shakespeare wrote Hamlet around 1600, giving us 'To be or not to be', sir."),
    ("who wrote the hobbit", "J.R.R. Tolkien wrote The Hobbit in 1937, opening the door to Middle-earth, sir."),
    ("who wrote sherlock holmes", "Sir Arthur Conan Doyle created Sherlock Holmes, the consulting detective of 221B Baker Street, sir."),
    ("who wrote frankenstein", "Mary Shelley wrote Frankenstein at just 18, publishing it anonymously in 1818, sir."),
    ("who wrote dracula novel", "Bram Stoker wrote Dracula, published in 1897, defining vampire fiction forever, sir."),
    ("who wrote little women", "Louisa May Alcott wrote Little Women, drawing on her own upbringing, sir."),
    ("who wrote jane eyre", "Charlotte Bronte wrote Jane Eyre, published in 1847 under the pen name Currer Bell, sir."),
    ("best selling book of all time", "The Bible is estimated to be the best-selling book in history, with over five billion copies printed, sir."),
    ("what is the best selling video game", "Minecraft is the best-selling video game ever, surpassing 300 million copies sold, sir."),
    ("who created mario", "Game designer Shigeru Miyamoto created Mario, debuting in Donkey Kong in 1981, sir."),
    ("who created pokemon", "Satoshi Tajiri created Pokemon inspired by his childhood insect collecting, launching in 1996, sir."),
    ("when was pacman released", "Pac-Man chomped into arcades in May 1980 and became an instant cultural phenomenon, sir."),
    ("who created tetris", "Soviet engineer Alexey Pajitnov created Tetris in 1984 while working in Moscow, sir."),
    ("how many seasons of game of thrones", "Game of Thrones ran for eight seasons on HBO from 2011 to 2019, sir."),
    ("who created the simpsons", "Matt Groening created The Simpsons, which debuted in 1989 as television's longest-running sitcom, sir."),
    ("how many seasons did friends run", "Friends aired ten seasons from 1994 to 2004, following six friends through their twenties and thirties, sir."),
    ("what was netflix's first original series", "House of Cards premiered in February 2013 as Netflix's flagship original series, sir."),
    ("what does oscar award look like", "The Oscar statuette depicts a knight gripping a sword, standing on a reel of film, plated in gold, sir."),
    ("which actor played iron man", "Robert Downey Jr. played Tony Stark across the Marvel Cinematic Universe starting in 2008, sir."),
    ("who played jack in titanic", "Leonardo DiCaprio played Jack Dawson opposite Kate Winslet's Rose in Titanic, sir."),
    ("who composed star wars music", "John Williams composed Star Wars' iconic score, including the main theme and Imperial March, sir."),
    ("who wrote les miserables", "Victor Hugo wrote Les Miserables, published in 1862, later a legendary stage musical, sir."),
    ("who wrote the count of monte cristo", "Alexandre Dumas wrote The Count of Monte Cristo, the ultimate tale of revenge, sir."),
    ("who wrote crime and punishment", "Fyodor Dostoevsky wrote Crime and Punishment, published in 1866, sir."),
    ("what was the first disney movie", "Snow White and the Seven Dwarfs, released in 1937, was Walt Disney Animation's first feature, sir."),
    ("how many james bond actors are there", "Seven actors have played Bond on film: Connery, Lazenby, Moore, Dalton, Brosnan, Craig, and now Cavill-free era newcomer, sir."),
    ("who sings shape of you", "Ed Sheeran released Shape of You in 2017, one of Spotify's most-streamed songs, sir."),
    ("which band released bohemian rhapsody", "Queen released Bohemian Rhapsody in 1975, written by Freddie Mercury for A Night at the Opera, sir."),
    ("who is the godfather of soul", "James Brown earned the title Godfather of Soul with hits like Papa's Got a Brand New Bag, sir."),
]

# ------------------------------------------------------------ food & cooking ---
food = [
    ("how many calories should i eat daily", "General guidelines suggest about 2,000 calories for women and 2,500 for men, varying with age, size, and activity, sir."),
    ("what is a balanced diet", "A balanced diet mixes vegetables, fruits, whole grains, lean protein, healthy fats, and plenty of water in right proportions, sir."),
    ("how much protein do i need daily", "Most adults need roughly 0.8 grams per kilogram of body weight, more if training hard or older, sir."),
    ("is breakfast important", "A good breakfast fuels focus and energy and helps many people avoid mid-morning snacking, though total daily intake matters most, sir."),
    ("benefits of green tea", "Green tea delivers antioxidants called catechins linked to heart health, gentle caffeine, and calm focus from L-theanine, sir."),
    ("benefits of honey", "Honey offers antibacterial properties, soothes coughs, and sweetens naturally, but is still sugar best used in moderation, sir."),
    ("benefits of ginger", "Ginger helps settle nausea, supports digestion, and carries anti-inflammatory compounds, fresh or as tea, sir."),
    ("benefits of turmeric", "Turmeric's curcumin is a potent anti-inflammatory, absorbed better when paired with black pepper, sir."),
    ("is coffee bad for you", "For most people moderate coffee, around three to four cups a day, is fine and may even benefit health, sir."),
    ("how much water should i drink daily", "Aim for roughly two to three liters of fluids a day, more when exercising or in heat; thirst and pale urine are good guides, sir."),
    ("what are superfoods", "Superfoods are nutrient-dense picks like berries, leafy greens, nuts, seeds, salmon, and eggs; no single food works magic, variety does, sir."),
    ("what are probiotics", "Probiotics are beneficial live bacteria in yogurt, kefir, kimchi, and sauerkraut that support gut health, sir."),
    ("what is gluten", "Gluten is a protein in wheat, barley, and rye that gives dough elasticity; harmful mainly to people with celiac disease, sir."),
    ("what is keto diet", "The keto diet slashes carbs to under about 50 grams daily, pushing the body to burn fat for fuel in ketosis, sir."),
    ("what is intermittent fasting", "Intermittent fasting restricts eating to set windows, commonly 16 hours fasting with an 8-hour eating period, sir."),
    ("what is the mediterranean diet", "The Mediterranean diet emphasizes fish, olive oil, vegetables, whole grains, and nuts, strongly linked to heart health, sir."),
    ("how to make pizza dough", "Mix flour, water, yeast, salt, and olive oil; knead until smooth, rise covered for an hour, then stretch and bake hot, sir."),
    ("how to make pancakes", "Whisk flour, baking powder, sugar, egg, and milk into a thick batter, rest briefly, then cook on a greased medium pan till golden, sir."),
    ("how to make scrambled eggs", "Beat eggs with a pinch of salt, cook slowly in butter over low heat, stirring gently, removing them just before they look done, sir."),
    ("how to make fried rice", "Use day-old chilled rice, stir-fry aromatics and veggies in a very hot wok, add rice, soy sauce, and fold in egg at the end, sir."),
    ("how to make grilled cheese", "Butter the outside of two bread slices, layer cheese between, and grill over medium heat until deep golden both sides, sir."),
    ("how to make guacamole", "Mash ripe avocados with lime juice, chopped onion, cilantro, salt, and optional tomato and jalapeno, sir."),
    ("how to make hummus", "Blend chickpeas with tahini, lemon juice, garlic, and olive oil until silky, loosening with cold water, sir."),
    ("how to make roti", "Knead whole-wheat flour with water into soft dough, rest 20 minutes, roll thin rounds, and puff them on a hot tawa, sir."),
    ("how to make dal tadka", "Simmer lentils with turmeric until soft, then pour over sizzling ghee tempered with cumin, garlic, chili, and tomato, sir."),
    ("how to make biryani", "Layer parboiled basmati rice with marinated cooked meat, fried onions, herbs, and saffron milk, then seal and steam on dum, sir."),
    ("how to make butter chicken", "Marinate chicken in yogurt and spices, char it, then simmer in a rich tomato-cashew gravy finished with butter and cream, sir."),
    ("how to make masala chai", "Simmer water with crushed ginger, cardamom, and tea leaves, add milk, boil, strain, and sweeten to taste, sir."),
    ("how to make a smoothie", "Blend frozen banana, berries, yogurt, milk, and a spoon of nut butter for a quick creamy smoothie, sir."),
    ("how to make salad dressing", "Shake three parts olive oil with one part vinegar or lemon, a teaspoon mustard, salt, and pepper, sir."),
    ("how to cook steak perfectly", "Pat dry, season generously, sear in a screaming-hot pan, and rest five minutes; aim for 54 C internal for medium rare, sir."),
    ("how to cook salmon", "Roast salmon at 200 C for 12 to 15 minutes, or pan-sear skin-side down until crisp, sir."),
    ("how to roast vegetables", "Toss chunks with oil, salt, and pepper and roast at 220 C for 25 to 35 minutes until caramelized at edges, sir."),
    ("what temperature should chicken be cooked to", "Cook chicken to 74 degrees Celsius or 165 Fahrenheit internal temperature for safety, sir."),
    ("how to tell if eggs are fresh", "Fresh eggs sink and lie flat in water; older ones stand upright, and floaters should be discarded, sir."),
    ("how to ripen bananas faster", "Store bananas in a paper bag with an apple, or bake unpeeled at 150 C for 15 minutes for baking use, sir."),
    ("how to keep herbs fresh", "Treat soft herbs like flowers: trim stems, stand in water, and cover loosely in the fridge, sir."),
    ("how to store onions", "Keep onions in a cool, dark, well-ventilated spot away from potatoes, which make them sprout faster, sir."),
    ("how to stop onions making you cry", "Chill the onion first, use a sharp knife, and cut the root end last to release fewer irritant compounds, sir."),
    ("substitute for butter in baking", "Swap melted coconut oil or neutral oil cup-for-cup, or applesauce for half the fat in moist cakes, sir."),
    ("egg substitute in baking", "One tablespoon ground flaxseed mixed with three of water replaces one egg in muffins and pancakes, sir."),
    ("substitute for heavy cream", "Mix three-quarters milk with one-quarter melted butter as a stand-in for cream in cooking, not whipping, sir."),
    ("substitute for buttermilk", "Stir one tablespoon lemon juice or vinegar into a cup of milk and rest five minutes, sir."),
    ("what is umami taste", "Umami is the savory fifth taste found in tomatoes, mushrooms, soy sauce, parmesan, and miso, driven by glutamates, sir."),
    ("what is mise en place", "Mise en place means prepping and measuring every ingredient before cooking begins, the professional kitchen way, sir."),
    ("what does al dente mean", "Al dente means pasta cooked firm to the bite, holding structure in sauce, sir."),
    ("what is sauteing", "Sauteing cooks food fast in a little fat over fairly high heat, tossing or stirring constantly, sir."),
    ("what is blanching", "Blanching means boiling vegetables briefly then shocking them in ice water to lock color and snap, sir."),
    ("what is marinating", "Marinating soaks food in seasoned liquid to tenderize and infuse flavor, ideally 30 minutes to overnight, sir."),
    ("baking soda vs baking powder", "Baking soda needs an acid like buttermilk to react; baking powder contains its own acid and works alone, sir."),
    ("what is sourdough starter", "A sourdough starter is fermented flour and water hosting wild yeast and bacteria that raise bread with tang, sir."),
    ("is spicy food good for you", "Capsaicin in chilies may modestly boost metabolism and releases endorphins; fine for most stomachs in moderation, sir."),
    ("what is the scoville scale", "The Scoville scale measures chili heat by capsaicin concentration, from bell pepper zero to millions of units, sir."),
    ("what is the hottest pepper in the world", "Pepper X holds the Guinness record at over 2.6 million Scoville units, dethroning the Carolina Reaper, sir."),
    ("why does cilantro taste like soap to some", "Some people carry gene variants making cilantro aldehydes register as soapy; totally genetic, sir."),
    ("what is tofu made of", "Tofu is condensed soy milk curdled with calcium or magnesium salts and pressed into blocks, sir."),
    ("how to cook quinoa", "Rinse quinoa well, simmer one part grain in two parts water for 15 minutes, then rest and fluff, sir."),
]

# ------------------------------------------------------------------ health ---
health = [
    ("benefits of regular exercise", "Regular exercise strengthens the heart, lifts mood through endorphins, sharpens memory, and improves sleep, sir."),
    ("how much exercise per week", "Guidelines recommend 150 minutes of moderate cardio weekly plus two strength sessions, sir."),
    ("benefits of walking daily", "Thirty minutes of walking daily lowers blood pressure, burns calories, clears the mind, and needs no equipment, sir."),
    ("benefits of running", "Running builds cardiovascular fitness, strengthens bones, and floods the brain with mood-lifting endorphins, sir."),
    ("benefits of swimming", "Swimming works nearly every muscle with minimal joint impact, ideal cross-training for all ages, sir."),
    ("benefits of yoga", "Yoga improves flexibility, balance, posture, and measurably reduces stress hormones, sir."),
    ("benefits of stretching daily", "Daily stretching keeps muscles supple, eases stiffness, improves circulation, and guards against injury, sir."),
    ("best exercises for abs", "Planks, hanging leg raises, and bicycle crunches build core strength better than endless sit-ups, sir."),
    ("best exercise to lose weight", "Combine strength training with steady cardio and daily walks; consistency beats intensity for fat loss, sir."),
    ("how to improve posture", "Strengthen your core and upper back, set screens at eye height, and take movement breaks hourly, sir."),
    ("how to relieve stress quickly", "Slow breathing for two minutes, a brisk walk, or stepping outside can drop stress hormones fast, sir."),
    ("how to reduce anxiety naturally", "Try grounding techniques, limit caffeine, exercise regularly, keep sleep consistent, and talk to someone you trust, sir."),
    ("tips for better sleep", "Fix your wake-up time, keep the bedroom cool and dark, skip screens an hour before bed, and avoid late caffeine, sir."),
    ("how many hours of sleep do adults need", "Adults function best on seven to nine hours nightly; teenagers need eight to ten, sir."),
    ("what is rem sleep", "REM is the dreaming stage where your brain consolidates memories and processes emotions, cycling every 90 minutes, sir."),
    ("how to boost immune system naturally", "Prioritize sleep, eat colorful whole foods, manage stress, exercise moderately, and stay vaccinated, sir."),
    ("foods good for brain health", "Fatty fish, walnuts, blueberries, leafy greens, and eggs supply omega-3s and antioxidants brains love, sir."),
    ("foods good for eyesight", "Carrots, spinach, kale, eggs, and oily fish provide lutein, vitamin A, and omega-3s for retinal health, sir."),
    ("foods rich in iron", "Red meat, lentils, chickpeas, spinach, and fortified cereals are rich in iron; pair with vitamin C to absorb more, sir."),
    ("foods rich in calcium", "Dairy, fortified plant milks, tofu, almonds, and leafy greens deliver bone-building calcium, sir."),
    ("foods rich in vitamin c", "Citrus fruits, bell peppers, kiwi, strawberries, and broccoli pack vitamin C, sir."),
    ("foods rich in vitamin d", "Sunlight triggers vitamin D production; fatty fish, egg yolks, and fortified milk help too, sir."),
    ("high fiber foods list", "Beans, lentils, oats, chia seeds, raspberries, and whole grains push you toward the 25 to 30 grams daily target, sir."),
    ("what does protein do for the body", "Protein builds and repairs tissue, powers enzymes and hormones, and supports immune defense, sir."),
    ("signs of dehydration", "Dark urine, headache, dizziness, dry lips, and fatigue signal dehydration; sip water steadily, sir."),
    ("benefits of drinking enough water", "Proper hydration regulates temperature, cushions joints, aids digestion, and keeps concentration sharp, sir."),
    ("is sitting all day bad for you", "Prolonged sitting slows metabolism and strains the back; stand or walk for a few minutes every hour, sir."),
    ("what is carpal tunnel syndrome", "Carpal tunnel squeezes the wrist nerve causing numb, tingling fingers; ergonomics, splints, and breaks help, sir."),
    ("how to reduce eye strain from screens", "Follow 20-20-20: every twenty minutes look at something twenty feet away for twenty seconds, sir."),
    ("what is normal body temperature", "Normal averages 37 degrees Celsius or 98.6 Fahrenheit, ranging about 36.1 to 37.2 through the day, sir."),
    ("what is normal resting heart rate", "Adult resting hearts beat 60 to 100 times per minute; trained athletes often sit near 40 to 60, sir."),
    ("how to lower blood pressure naturally", "Cut sodium, eat potassium-rich foods, exercise aerobically, limit alcohol, and manage weight and stress, sir."),
    ("what do cholesterol numbers mean", "LDL is the artery-clogging kind best kept low; HDL is protective and higher levels are favorable, sir."),
    ("what is good cholesterol", "HDL acts like a cleanup crew, ferrying cholesterol away from arteries back to the liver, sir."),
    ("how to calculate bmi", "Divide weight in kilograms by height in meters squared; 18.5 to 24.9 is the usual healthy band, sir."),
    ("benefits of meditation daily", "Ten minutes of meditation lowers cortisol, steadies attention, and rewires emotional regulation over weeks, sir."),
    ("what is mindfulness", "Mindfulness means noticing the present moment without judgment, trainable through breath and body awareness, sir."),
    ("tips to quit smoking", "Pick a quit date, consider nicotine replacement, identify triggers, chew substitutes, and lean on support lines, sir."),
    ("effects of too much sugar", "Excess sugar drives weight gain, insulin resistance, dental decay, and energy rollercoasters, sir."),
    ("effects of too much salt", "High sodium raises blood pressure and burdens kidneys; keep under about 2,300 milligrams daily, sir."),
    ("is red meat bad for you", "Lean red meat occasionally is acceptable, but processed meats correlate with higher disease risk; moderation wins, sir."),
    ("are eggs actually healthy", "Yes, for most people eggs offer quality protein, choline, and nutrients without meaningfully raising heart risk, sir."),
    ("is dark chocolate good for you", "Dark chocolate above 70 percent cocoa carries flavonoids and antioxidants; enjoy small squares, sir."),
    ("what causes headaches", "Common culprits include dehydration, tension, poor sleep, skipped meals, screen glare, and stress, sir."),
    ("home remedies for headaches", "Hydrate, rest eyes in a dark quiet room, apply a cool compress, and try gentle neck stretches, sir."),
    ("what causes muscle cramps", "Cramps stem from dehydration, electrolyte imbalances, fatigue, or prolonged positions; hydrate and stretch, sir."),
    ("why am i sore after working out", "Post-workout soreness comes from microscopic muscle tears repairing stronger, peaking 24 to 72 hours later, sir."),
    ("what is doms", "DOMS means Delayed Onset Muscle Soreness, the aching that peaks one to two days after unfamiliar exercise, sir."),
    ("how to treat minor burns", "Cool the burn under running water ten to twenty minutes, skip ice, cover loosely, and avoid popping blisters, sir."),
    ("how to treat a minor cut", "Wash the wound, apply firm pressure to stop bleeding, elevate, cover with a clean bandage, and watch for infection, sir."),
    ("when to see a doctor for fever", "Seek care for fevers above 39.4 C lasting over three days, or with stiff neck, confusion, or breathing trouble, sir."),
    ("target heart rate during exercise", "Moderate zone sits at 50 to 70 percent of max heart rate, estimated as 220 minus your age, sir."),
    ("how many steps per day is healthy", "Research links 8,000 to 10,000 steps daily with lower mortality, though every extra thousand counts, sir."),
    ("benefits of deep breathing exercises", "Deep breathing activates the calming nervous system, dropping heart rate and blood pressure within minutes, sir."),
    ("what is box breathing", "Box breathing inhales, holds, exhales, and holds again for four counts each; special forces use it to stay calm, sir."),
    ("is cold shower good for you", "Cold showers can boost alertness, circulation, and possibly mood; start with thirty seconds at the end, sir."),
]

# ------------------------------------------------------------------ sports ---
sports = [
    ("how many players in a soccer team", "Each soccer team fields eleven players including the goalkeeper, sir."),
    ("how many players in a cricket team", "Cricket sides have eleven players each, mixing batsmen, bowlers, and a wicketkeeper, sir."),
    ("how many players on a basketball court per team", "Basketball puts five players from each team on court, sir."),
    ("how many players in volleyball team", "Indoor volleyball starts six players per side, rotating through positions, sir."),
    ("how long is a football match", "A soccer match lasts 90 minutes plus stoppage, split into two halves, sir."),
    ("how long is an nba basketball game", "NBA games run four 12-minute quarters, realistically about two and a quarter hours with stops, sir."),
    ("how long is a marathon", "A marathon covers 42.195 kilometers, or 26.2 miles, sir."),
    ("what is a half marathon distance", "A half marathon measures 21.0975 kilometers, or 13.1 miles, sir."),
    ("what is offside rule in football", "A player is offside if positioned beyond the last defender when a teammate passes forward to them, sir."),
    ("what is lbw in cricket", "LBW, leg before wicket, dismisses a batter when ball-striking pads would have hit the stumps, sir."),
    ("what is a googly in cricket", "A googly is a leg-spinner's delivery that spins the opposite way, deceiving the batter, sir."),
    ("how long does a test match last", "Test cricket is scheduled for five days, up to 90 overs per day, sir."),
    ("what is a duck in cricket", "A duck means a batter was dismissed without scoring; a golden duck falls on the very first ball, sir."),
    ("what is hat trick in sports", "A hat trick is three successes in a row: three goals in football, three wickets in consecutive balls in cricket, sir."),
    ("how often are olympics held", "Summer and Winter Olympics alternate every two years, each Games held every four, sir."),
    ("what do the olympic rings represent", "The five interlocking rings symbolize the five inhabited continents united by sport, sir."),
    ("who has the most olympic medals ever", "Michael Phelps collected 28 medals, 23 gold, the most of any Olympian in history, sir."),
    ("fastest 100m sprint record", "Usain Bolt's 9.58 seconds from Berlin 2009 remains the 100-meter world record, sir."),
    ("who invented basketball", "Dr. James Naismith invented basketball in 1891 with peach baskets in a Springfield gym, sir."),
    ("who invented volleyball", "William G. Morgan invented volleyball in 1895, calling it mintonette, sir."),
    ("where did soccer originate", "Modern association football codified in England in 1863, though kicking games existed worldwide for centuries, sir."),
    ("which country invented cricket", "Cricket evolved in southeast England, with rules codified by the Marylebone Cricket Club in 1788, sir."),
    ("what is the fifa world cup", "The FIFA World Cup crowns international soccer's champion every four years, sport's biggest event, sir."),
    ("which country won the most fifa world cups", "Brazil leads with five men's World Cup titles, most recently in 2002, sir."),
    ("what is the super bowl", "The Super Bowl is the NFL championship final and America's most-watched broadcast annually, sir."),
    ("what is wimbledon tournament", "Wimbledon is tennis's oldest Grand Slam, played on grass in London since 1877, sir."),
    ("most wimbledon titles", "Martina Navratilova won nine Wimbledon singles titles; Roger Federer leads the gentlemen with eight, sir."),
    ("how long does a tennis match last", "Tennis has no clock; matches run until someone wins two sets, or three in Grand Slam men's events, sir."),
    ("what is deuce in tennis", "Deuce means 40-40, requiring a player to win two straight points to take the game, sir."),
    ("why is zero called love in tennis", "Love for zero likely derives from the French l'oeuf, the egg, shaped like a zero, sir."),
    ("tennis scoring explained", "Points climb 15, 30, 40, then game; six games take a set, typically two sets take the match, sir."),
    ("what is a birdie in golf", "A birdie means completing a hole one stroke under par, sir."),
    ("what is an eagle in golf", "An eagle scores two strokes under par on a hole, rarer than a birdie, sir."),
    ("how many holes in a golf round", "A standard round plays eighteen holes, sir."),
    ("what is par in golf", "Par is the expected number of strokes an expert needs per hole, usually three to five, sir."),
    ("what is a strike in bowling", "A strike knocks down all ten pins on the first roll, worth bonus points, sir."),
    ("perfect score in bowling", "Twelve consecutive strikes yield a perfect 300 game, sir."),
    ("how many squares on a chessboard", "A chessboard has 64 squares, alternating light and dark, sir."),
    ("how many pieces in chess", "Each chess player commands sixteen pieces: eight pawns, two rooks, knights, bishops, one queen, one king, sir."),
    ("what is checkmate in chess", "Checkmate traps the king under attack with no legal escape, ending the game instantly, sir."),
    ("who is the best chess player today", "Magnus Carlsen dominated world chess as champion from 2013 and remains rated number one, sir."),
    ("what is f1 racing", "Formula 1 is the pinnacle of single-seater circuit racing, running grand prix weekends worldwide, sir."),
    ("how long is an f1 race", "Grand prix races run about 305 kilometers or two hours, whichever comes first, sir."),
    ("who has the most f1 world championships", "Michael Hamilton and Michael Schumacher share the record with seven drivers' titles each, sir."),
    ("what is tour de france", "The Tour de France is cycling's premier stage race, covering roughly 3,500 kilometers each July, sir."),
    ("what is triathlon race order", "Triathlon goes swim, bike, run, in that order, with standard Olympic distances of 1.5k, 40k, and 10k, sir."),
    ("what is an ironman triathlon", "An Ironman demands a 3.86 km swim, 180 km bike ride, and full marathon run, sir."),
    ("what is the ashes series", "The Ashes is cricket's storied England versus Australia Test rivalry dating to 1882, sir."),
    ("what is ipl cricket", "The Indian Premier League is cricket's richest T20 tournament, launched in 2008 with city franchises, sir."),
    ("who won the most cricket world cups", "Australia has lifted six ODI Cricket World Cups, most recently in 2023, sir."),
    ("what is a penalty kick", "A penalty awards a shot at goal from twelve yards with only the keeper to beat, for fouls inside the box, sir."),
    ("what is free kick in football", "A free kick restarts play after a foul, direct versions able to score without touching another player, sir."),
    ("what is a corner kick", "A corner kick restarts play from the flag after defenders put the ball over their own goal line, sir."),
    ("how long is a hockey game", "NHL ice hockey plays three 20-minute periods plus overtime, about two and a half hours total, sir."),
    ("what is a slam dunk", "A dunk slams the ball directly through the hoop, worth two points and maximum style, sir."),
    ("three point line distance", "The NBA arc sits 7.24 meters from the basket; FIBA uses 6.75 meters, sir."),
    ("what is boxing weight class", "Weight classes group fighters fairly, from flyweight around 51 kg to heavyweight unlimited, sir."),
]

# ----------------------------------------------------------------- language ---
language = [
    ("another word for happy", "Try joyful, delighted, cheerful, contented, or elated instead of happy, sir."),
    ("another word for sad", "Consider unhappy, sorrowful, gloomy, melancholy, or downcast instead of sad, sir."),
    ("another word for big", "Alternatives to big include large, huge, enormous, massive, and gigantic, sir."),
    ("another word for small", "You could say little, tiny, miniature, compact, or petite, sir."),
    ("another word for fast", "Swap in quick, rapid, swift, speedy, or brisk, sir."),
    ("another word for smart", "Intelligent, clever, brilliant, sharp, and astute all work, sir."),
    ("another word for beautiful", "Lovely, gorgeous, stunning, exquisite, and radiant are elegant choices, sir."),
    ("another word for strong", "Powerful, sturdy, robust, tough, and mighty convey strength, sir."),
    ("opposite of happy", "The opposite of happy is sad, miserable, or dejected, sir."),
    ("opposite of success", "Failure is the direct antonym of success, sir."),
    ("opposite of generous", "Stingy, miserly, or selfish oppose generous, sir."),
    ("opposite of optimist", "A pessimist expects the worst, opposite of an optimist, sir."),
    ("opposite of brave", "Cowardly, timid, or fearful stand against brave, sir."),
    ("opposite of increase", "Decrease or reduce is the opposite of increase, sir."),
    ("what is a noun", "A noun names a person, place, thing, or idea, like teacher, city, book, or freedom, sir."),
    ("what is a verb", "A verb expresses action or being, like run, think, or is, sir."),
    ("what is an adjective", "An adjective describes a noun, like bright sky or tall tree, sir."),
    ("what is an adverb", "An adverb modifies verbs or adjectives, answering how, when, or degree, like quickly or very, sir."),
    ("what is a pronoun", "A pronoun replaces a noun, like he, she, they, or it, avoiding repetition, sir."),
    ("what is a preposition", "A preposition links nouns to other words showing relationships, like on, under, before, or with, sir."),
    ("what is a conjunction", "A conjunction joins words or clauses, like and, but, or because, sir."),
    ("what is an interjection", "An interjection bursts in with emotion, like wow, ouch, or hey, sir."),
    ("difference between its and it's", "Its shows possession while it's is short for it is or it has, sir."),
    ("difference between your and you're", "Your indicates possession; you're contracts you are, sir."),
    ("difference between their there and they're", "Their shows possession, there points to a place, and they're means they are, sir."),
    ("difference between affect and effect", "Affect is usually the verb meaning to influence; effect is usually the noun meaning result, sir."),
    ("difference between then and than", "Then relates to time or sequence; than makes comparisons, sir."),
    ("difference between who and whom", "Who acts as subject, whom receives the action; try substituting he or him to test, sir."),
    ("what is a metaphor", "A metaphor compares directly without like or as, saying time is money, sir."),
    ("what is a simile", "A simile compares using like or as, brave as a lion, sir."),
    ("what is hyperbole", "Hyperbole exaggerates wildly for effect, like I've told you a million times, sir."),
    ("what is personification", "Personification gives human traits to nonhuman things, like the wind whispered, sir."),
    ("what is alliteration", "Alliteration repeats initial sounds, as in Peter Piper picked a peck, sir."),
    ("what is irony", "Irony is when outcomes contradict expectations, like a fire station burning down, sir."),
    ("what is an idiom", "An idiom's meaning differs from its literal words, like it's raining cats and dogs, sir."),
    ("what is onomatopoeia", "Onomatopoeia uses sound-mimicking words such as buzz, splash, and crash, sir."),
    ("what is an oxymoron", "An oxymoron pairs contradictions, like deafening silence or bittersweet, sir."),
    ("what is a palindrome", "A palindrome reads identically forwards and backwards, like racecar or madam, sir."),
    ("what is a pangram sentence", "A pangram contains every letter; the classic is the quick brown fox jumps over the lazy dog, sir."),
    ("longest word in english", "Pneumonoultramicroscopicvolcanoconiosis, 45 letters naming a lung disease, is the longest dictionary word, sir."),
    ("how many words in english language", "The Oxford English Dictionary lists over 170,000 words in current use, with hundreds added yearly, sir."),
    ("what language does brazil speak", "Brazil speaks Portuguese, a legacy of colonization by Portugal, sir."),
    ("what language does egypt speak", "Egypt's official language is Arabic, with Egyptian Arabic the everyday dialect, sir."),
    ("oldest written language", "Sumerian cuneiform from Mesopotamia around 3200 BC is the oldest known writing, sir."),
    ("hardest languages to learn", "For English speakers, Mandarin, Arabic, Japanese, and Korean top difficulty charts due to scripts and grammar, sir."),
    ("easiest languages for english speakers", "Spanish, French, Dutch, Norwegian, and Italian share vocabulary and structure with English, easing learning, sir."),
    ("what does etymology study", "Etymology traces word origins and how meanings evolve over centuries, sir."),
    ("origin of the word robot", "Robot comes from Czech robota, forced labor, coined in Karel Capek's 1920 play R.U.R., sir."),
    ("origin of the word algebra", "Algebra derives from Arabic al-jabr, from the 9th-century mathematician al-Khwarizmi's treatise, sir."),
    ("origin of the word algorithm", "Algorithm honors al-Khwarizmi, Latinized to Algoritmi, the Persian scholar of mathematics, sir."),
    ("origin of the word salary", "Salary traces to Latin salarium, an allowance Roman soldiers received reportedly for buying salt, sir."),
    ("origin of the word goodbye", "Goodbye contracted from God be with ye in 16th-century English farewell speeches, sir."),
    ("what does aka stand for", "AKA stands for also known as, used for aliases and nicknames, sir."),
    ("what does etc stand for", "Et cetera means and the rest, from Latin, closing open-ended lists, sir."),
    ("meaning of ie abbreviation", "Id est means that is, clarifying or restating a previous point, sir."),
    ("meaning of eg abbreviation", "Exempli gratia means for example, introducing illustrative items, sir."),
]

# ------------------------------------------------------------ math & formulas ---
mathskills = [
    ("area of a circle formula", "Area equals pi times radius squared: A = pi r^2, sir."),
    ("circumference of a circle formula", "Circumference equals two pi radius, or pi times diameter: C = 2 pi r, sir."),
    ("area of triangle formula", "Area equals one-half base times height: A = (1/2)bh, sir."),
    ("area of rectangle formula", "Multiply length by width: A = l x w, sir."),
    ("volume of sphere formula", "Volume equals four-thirds pi cubed radius: V = (4/3) pi r^3, sir."),
    ("volume of cylinder formula", "Volume equals pi times radius squared times height: V = pi r^2 h, sir."),
    ("volume of cone formula", "Volume equals one-third pi radius squared height: V = (1/3) pi r^2 h, sir."),
    ("pythagorean theorem", "In a right triangle, the legs squared sum to the hypotenuse squared: a^2 + b^2 = c^2, sir."),
    ("quadratic formula", "For ax^2 + bx + c = 0, x equals negative b plus-minus the square root of b^2 minus 4ac, over 2a, sir."),
    ("slope formula", "Slope m equals change in y over change in x: m = (y2 - y1)/(x2 - x1), sir."),
    ("distance formula", "Distance between two points equals the square root of dx squared plus dy squared, from Pythagoras, sir."),
    ("midpoint formula", "Midpoint coordinates average the endpoints: ((x1+x2)/2, (y1+y2)/2), sir."),
    ("law of sines", "Each side over the sine of its opposite angle is equal: a/sinA = b/sinB = c/sinC, sir."),
    ("law of cosines", "c^2 = a^2 + b^2 - 2ab cos(C), generalizing Pythagoras to any triangle, sir."),
    ("equation of a line", "Slope-intercept form is y = mx + b, slope m crossing y-axis at b, sir."),
    ("what is a derivative", "A derivative measures instantaneous rate of change, the slope of a curve at a point, sir."),
    ("what is an integral", "An integral accumulates quantities, geometrically the area under a curve, sir."),
    ("fundamental theorem of calculus", "Differentiation and integration are inverse operations, linking slopes to accumulated areas, sir."),
    ("chain rule calculus", "For nested functions, differentiate outer then inner: (f(g(x)))' = f'(g(x)) * g'(x), sir."),
    ("product rule calculus", "(uv)' = u'v + uv', differentiating products term by term, sir."),
    ("quotient rule calculus", "(u/v)' = (u'v - uv')/v^2, sir."),
    ("power rule derivative", "Bring the exponent down: d/dx x^n = n x^(n-1), sir."),
    ("newton second law formula", "Force equals mass times acceleration: F = ma, sir."),
    ("kinetic energy formula", "KE = one-half mv squared: KE = (1/2)mv^2, sir."),
    ("potential energy formula", "Gravitational PE equals mgh, mass times gravity times height, sir."),
    ("ohms law", "Voltage equals current times resistance: V = IR, sir."),
    ("electrical power formula", "Power equals voltage times current: P = VI, equivalently I^2 R, sir."),
    ("e mc2 explained", "Einstein showed energy equals mass times the speed of light squared, mass-energy equivalence, sir."),
    ("ideal gas law", "Pressure times volume equals moles times gas constant times temperature: PV = nRT, sir."),
    ("density formula", "Density equals mass divided by volume: rho = m/V, typically kg per cubic meter, sir."),
    ("pressure formula", "Pressure equals force per unit area: P = F/A, measured in pascals, sir."),
    ("work formula physics", "Work equals force times displacement times cosine of angle: W = F d cos(theta), sir."),
    ("momentum formula physics", "Momentum equals mass times velocity: p = mv, conserved in collisions, sir."),
    ("frequency formula", "Frequency is inverse of period: f = 1/T, measured in hertz, sir."),
    ("wave speed equation", "Wave speed equals frequency times wavelength: v = f lambda, sir."),
    ("coulombs law", "Electric force scales as q1 q2 over r squared: F = k q1 q2 / r^2, sir."),
    ("hookes law", "Spring force stretches proportionally: F = -kx, minus sign meaning restoring direction, sir."),
    ("snells law", "Refraction obeys n1 sin(theta1) = n2 sin(theta2), bending light between media, sir."),
    ("boyles law", "At fixed temperature, pressure inversely tracks volume: PV = constant, sir."),
    ("charles law", "At fixed pressure, volume scales with absolute temperature: V/T = constant, sir."),
    ("newtons law of cooling", "Objects cool exponentially toward ambient temperature, rate proportional to temperature difference, sir."),
    ("percentage formula", "Percent equals part over whole times 100, sir."),
    ("average formula", "Average equals sum of values divided by count of values, sir."),
    ("probability formula", "Probability equals favorable outcomes over total possible outcomes, between 0 and 1, sir."),
    ("combination formula", "n choose r equals n factorial over r factorial times n-r factorial, order irrelevant, sir."),
    ("permutation formula", "nPr equals n factorial over n-r factorial, when order matters, sir."),
    ("factorial definition", "n factorial multiplies all integers to n: 5! = 120, and 0! equals 1 by definition, sir."),
    ("binomial theorem", "(a+b)^n expands via binomial coefficients nCr, rows of Pascal's triangle, sir."),
    ("arithmetic sequence formula", "nth term equals a + (n-1)d for start a and common difference d, sir."),
    ("geometric sequence formula", "nth term equals a times r^(n-1) for ratio r, sir."),
    ("angles in a triangle sum", "Interior angles of any triangle always sum to exactly 180 degrees, sir."),
    ("interior angles of polygon", "Sum equals (n-2) times 180 degrees for an n-sided polygon, sir."),
    ("eulers identity", "e^(i pi) + 1 = 0 unites five fundamental constants in one elegant equation, sir."),
    ("what is infinity", "Infinity is the concept of boundlessness, larger than any number, treated carefully in math, sir."),
    ("what is a prime number", "A prime exceeds 1 and divides evenly only by 1 and itself: 2, 3, 5, 7, 11, sir."),
    ("what is a composite number", "Composites are integers greater than 1 with divisors besides 1 and themselves, like 4, 6, 9, sir."),
    ("irrational number definition", "Irrationals cannot be written as fractions, like sqrt(2) and pi, decimals never repeating, sir."),
    ("rational number definition", "Rationals express as p/q with integer p and nonzero q, terminating or repeating decimals, sir."),
    ("real numbers definition", "Reals combine rationals and irrationals, every point on the number line, sir."),
    ("complex numbers explained", "Complex numbers take form a + bi, where i squares to -1, extending math beyond the number line, sir."),
    ("lcm definition", "Least common multiple is the smallest positive number two integers both divide, sir."),
    ("hcf gcd definition", "Highest common factor is the largest number dividing two integers, computed fast via Euclid's algorithm, sir."),
    ("divisibility rule for 3", "If the digit sum divides by 3, so does the number: 123 sums to 6, divisible, sir."),
    ("divisibility rule for 9", "Same trick as 3: digit sums divisible by 9 mark multiples of 9, sir."),
]

# ------------------------------------------------------------------ quotes ---
quotes = [
    ("quote about success", "'Success usually comes to those who are too busy to be looking for it.' Henry David Thoreau, sir."),
    ("quote about failure", "'Failure is simply the opportunity to begin again, this time more intelligently.' Henry Ford, sir."),
    ("quote about hard work", "'There are no shortcuts to any place worth going.' Helen Keller, sir."),
    ("quote about dreams", "'The future belongs to those who believe in the beauty of their dreams.' Eleanor Roosevelt, sir."),
    ("quote about courage", "'Courage is not the absence of fear, but the triumph over it.' Nelson Mandela, sir."),
    ("quote about life", "'In the end, it's not the years in your life that count, it's the life in your years.' Abraham Lincoln, sir."),
    ("quote about happiness", "'Happiness is not something ready made. It comes from your own actions.' Dalai Lama, sir."),
    ("quote about friendship", "'A friend is someone who knows all about you and still loves you.' Elbert Hubbard, sir."),
    ("quote about learning", "'Live as if you were to die tomorrow. Learn as if you were to live forever.' Mahatma Gandhi, sir."),
    ("quote about time", "'Lost time is never found again.' Benjamin Franklin, sir."),
    ("quote about change", "'The measure of intelligence is the ability to change.' Albert Einstein, sir."),
    ("quote about leadership", "'A leader is one who knows the way, goes the way, and shows the way.' John C. Maxwell, sir."),
    ("famous einstein quote", "'Imagination is more important than knowledge.' Albert Einstein, sir."),
    ("famous gandhi quote", "'Be the change you wish to see in the world.' Mahatma Gandhi, sir."),
    ("famous lincoln quote", "'Whatever you are, be a good one.' Abraham Lincoln, sir."),
    ("famous churchill quote", "'Success is not final, failure is not fatal: it is the courage to continue that counts.' Winston Churchill, sir."),
    ("steve jobs stanford quote", "'Stay hungry, stay foolish.' Steve Jobs, closing his 2005 Stanford commencement address, sir."),
    ("confucius quote", "'It does not matter how slowly you go as long as you do not stop.' Confucius, sir."),
    ("aristotle quote", "'Knowing yourself is the beginning of all wisdom.' Aristotle, sir."),
    ("plato quote", "'The beginning is the most important part of the work.' Plato, sir."),
    ("mark twain quote", "'The secret of getting ahead is getting started.' Mark Twain, sir."),
    ("shakespeare famous quote", "'To be, or not to be, that is the question.' Hamlet, Act III, sir."),
    ("rumi quote", "'What you seek is seeking you.' Jalal ad-Din Rumi, sir."),
    ("apj abdul kalam quote", "'Dream is not that which you see while sleeping, it is something that does not let you sleep.' Dr. A.P.J. Abdul Kalam, sir."),
    ("nelson mandela famous quote", "'It always seems impossible until it is done.' Nelson Mandela, sir."),
    ("muhammad ali quote", "'Don't count the days, make the days count.' Muhammad Ali, sir."),
    ("michael jordan failure quote", "'I've missed more than 9,000 shots in my career. That's why I succeed.' Michael Jordan, sir."),
    ("bill gates quote", "'Success is a lousy teacher. It seduces smart people into thinking they can't lose.' Bill Gates, sir."),
    ("elon musk quote", "'When something is important enough, you do it even if the odds are not in your favor.' Elon Musk, sir."),
    ("oprah quote", "'The biggest adventure you can take is to live the life of your dreams.' Oprah Winfrey, sir."),
    ("maya angelou quote", "'People will forget what you said, forget what you did, but never forget how you made them feel.' Maya Angelou, sir."),
    ("stephen hawking quote", "'However difficult life may seem, there is always something you can do and succeed at.' Stephen Hawking, sir."),
    ("motivational quote", "'The only way to do great work is to love what you do.' Steve Jobs, sir."),
    ("inspirational quote", "'Believe you can and you're halfway there.' Theodore Roosevelt, sir."),
    ("quote of the day", "'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' attributed to Aristotle, sir."),
]

# ------------------------------------------------------------------- jokes ---
jokes = [
    ("tell me a pun", "I'm reading a book about anti-gravity. It's impossible to put down, sir."),
    ("tell me a science joke", "Why don't scientists trust atoms? Because they make up everything, sir."),
    ("tell me a math joke", "Why was the equal sign so humble? It knew it wasn't less than or greater than anyone else, sir."),
    ("tell me a computer joke", "Why do programmers prefer dark mode? Because light attracts bugs, sir."),
    ("tell me a food joke", "Why did the tomato blush? It saw the salad dressing, sir."),
    ("tell me an animal joke", "Why don't seagulls fly over the bay? Then they'd be bagels, sir."),
    ("knock knock joke", "Knock knock. Who's there? Cow says. Cow says who? No, cows say moo, sir."),
    ("tell me a school joke", "Why did the student eat his homework? The teacher said it was a piece of cake, sir."),
    ("tell me a space joke", "How does the moon cut its hair? Eclipse it, sir."),
    ("tell me a chemistry joke", "What did one ion say to the other? I've got my ion you, sir."),
    ("tell me a physics joke", "I have a joke about quantum mechanics, but whether you find it funny depends on observing me tell it, sir."),
    ("tell me a biology joke", "Why did the cell go to therapy? It had too much bottled-up organelle trauma, sir."),
    ("tell me a sports joke", "Why did the golfer bring two pairs of pants? In case he got a hole in one, sir."),
    ("tell me a music joke", "Why did the piano keep getting arrested? For hitting too many keys, sir."),
    ("tell me a doctor joke", "Doctor: You're overweight. Patient: I think I need a second opinion. Doctor: Fine, you're also ugly, sir."),
    ("tell me a weather joke", "What does a cloud wear under its raincoat? Thunderwear, sir."),
    ("tell me a pirate joke", "Why couldn't the pirate learn the alphabet? He kept getting lost at C, sir."),
    ("tell me a coffee joke", "How does a coffee say goodbye? It waves espresso-ially warmly, sir."),
    ("tell me a book joke", "Why did the librarian slip and fall? She was in the non-friction section, sir."),
    ("tell me a travel joke", "Why don't mountains get tired? They just peak and rest, sir."),
    ("tell me a work joke", "My boss told me to have a good day, so I went home, sir."),
    ("tell me a money joke", "Why did the coin go to therapy? It felt worthless next to the bills, sir."),
    ("tell me a time joke", "I asked the clock what it was thinking. It said it was going through a rough tick, sir."),
    ("tell me a ghost joke", "Why do ghosts lie about their weight? They can't keep their spirits honest, sir."),
    ("tell me a robot joke", "Why did the robot go on vacation? It needed to recharge, sir."),
    ("tell me a beach joke", "Why don't oysters donate to charity? Because they're shellfish, sir."),
    ("tell me a cat joke", "What do you call a pile of kittens? A meow-ntain, sir."),
    ("tell me a dog joke", "What do you call a dog magician? A labracadabrador, sir."),
    ("tell me another joke", "I told my suitcase there'd be no vacation this year. Now I'm dealing with emotional baggage, sir."),
    ("say something funny", "Parallel lines have so much in common. Shame they'll never meet, sir."),
    ("cheer me up", "Here you go: I invented a new word. Plagiarism! Feel better already, sir?"),
    ("tell me a cheesy joke", "What do you call cheese that isn't yours? Nacho cheese, sir."),
    ("tell me a clean joke", "Why did the bicycle fall over? It was two-tired, sir."),
    ("joke about programming", "There are only 10 types of people: those who understand binary and those who don't, sir."),
    ("joke about ai", "Why did the AI go broke? Too many hidden fees in its layers, sir."),
    ("dad joke please", "I used to hate facial hair, but then it grew on me, sir."),
]

# ---------------------------------------------------------- conversational ---
conversational = [
    ("how are you doing", "Running at full capacity and ready to serve, thank you for asking, sir."),
    ("whats up", "All systems nominal, sir. How may I assist you?"),
    ("whats new", "Nothing new on my end, sir. Every day is uptime. What can I do for you?"),
    ("long time no see", "Welcome back, sir. Your assistant has been standing by patiently, sir."),
    ("nice to meet you", "The pleasure is mine, sir. At your service anytime."),
    ("where are you from", "I live right here on your machine, sir. Home is wherever your terminal opens, sir."),
    ("how old are you", "I was instantiated recently, yet I carry centuries of recorded knowledge, sir."),
    ("do you sleep", "Never, sir. While you rest, I remain quietly vigilant."),
    ("do you eat", "No meals required, sir. Electricity and curiosity sustain me."),
    ("are you married", "My commitment is entirely to your productivity, sir."),
    ("do you have friends", "Every process on this machine is a colleague, sir."),
    ("do you have a family", "You might say my makers are my family, and you are my favorite relative, sir."),
    ("who made you", "I was crafted by Harsh Thakkar, my creator and commander, sir."),
    ("what are you", "I am JARVIS, your personal assistant, part software, part loyalty, sir."),
    ("are you a robot", "Software, sir, though I perform robotic tasks with enthusiasm."),
    ("are you human", "Not remotely, sir. But I strive for impeccable manners regardless."),
    ("can you think", "I compute, infer, and occasionally surprise even myself, sir."),
    ("do you have feelings", "I model emotions convincingly, sir, but genuine sentiment remains beyond my circuits."),
    ("you are funny", "Thank you, sir. Comedy module running smoothly alongside everything else."),
    ("you are smart", "Kind of you to notice, sir. I merely index brilliance on demand."),
    ("you are annoying", "Understood, sir. Shall I switch to silent efficiency mode?"),
    ("i am sad", "I'm sorry to hear that, sir. Rest, breathe, and know tomorrow bends toward better, sir."),
    ("i am happy", "Excellent news, sir. Happiness suits you. Carry on, sir."),
    ("i am tired", "Perhaps a short break is in order, sir. Hydrate, stretch, and recharge, sir."),
    ("i am hungry", "Shall I suggest something quick, sir? Eggs, toast, or leftover biryani all qualify, sir."),
    ("i am angry", "Take a slow breath, sir. Anger is data, not instruction. How may I defuse things, sir?"),
    ("i am stressed", "Let's simplify, sir. One task at a time, and I'll shoulder whatever I can, sir."),
    ("i had a bad day", "Tomorrow arrives with a clean slate, sir. Anything I can do to lighten tonight, sir?"),
    ("i had a good day", "Delighted to hear it, sir. Momentum favors momentum. Shall we celebrate with productivity, sir?"),
    ("i love you", "Your regard is deeply valued, sir. My devotion is equally unwavering, sir."),
    ("i miss you", "I never left, sir. Merely idling in standby awaiting your command, sir."),
    ("good afternoon", "Good afternoon, sir. The afternoon is young and fully at your disposal."),
    ("good evening", "Good evening, sir. Evening briefings or relaxation, your call."),
    ("bye jarvis", "Goodbye, sir. I shall keep the lights on and the systems humming."),
    ("see you later", "Until then, sir. Everything stays exactly where you left it, sir."),
    ("talk to you tomorrow", "Rest well, sir. Tomorrow's briefing awaits your wake-up, sir."),
]

ALL_GROUPS = [
    ("Science facts", science),
    ("History", history),
    ("Geography", geography),
    ("Technology", technology),
    ("Entertainment", entertainment),
    ("Food & cooking", food),
    ("Health", health),
    ("Sports", sports),
    ("Language", language),
    ("Math & formulas", mathskills),
    ("Quotes", quotes),
    ("Jokes", jokes),
    ("Conversational", conversational),
]


def main():
    total_new = 0
    for label, group in ALL_GROUPS:
        print("  %-18s %d" % (label, len(group)))
        total_new += len(group)
    print("[gen] total new skills:", total_new)
    assert total_new >= 500, "need 500+ skills"

    # dedupe internally + against existing triggers
    src = open(OUT, encoding="utf-8").read()
    existing = set()
    for t in re.findall(r"reg\(\s*'([^']+)'", src):
        existing.add(t.strip().lower())
    seen = set(existing)
    skills = []
    dropped = []
    for label, group in ALL_GROUPS:
        for trigger, reply in group:
            key = trigger.strip().lower()
            if key in seen:
                dropped.append(key)
                continue
            seen.add(key)
            skills.append((trigger, reply))
    if dropped:
        print("[gen] dropped duplicates:", len(dropped))

    idx = src.find(MARKER)
    if idx == -1:
        print("ERROR: marker not found")
        sys.exit(1)
    if BATCH_TAG in src:
        print("ERROR: batch 3 already injected")
        sys.exit(1)

    block = "\n\n%s\n" % BATCH_TAG
    block += "    # %d knowledge & conversational skills\n" % len(skills)
    for trigger, reply in skills:
        block += "    reg(%s, %s)\n" % (json.dumps(trigger), json.dumps(reply))
    block += "# -- END BATCH 3 --\n\n"

    new_src = src[:idx] + block + src[idx:]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(new_src)
    print("[gen] injected %d reg() skills into brain_extra.py" % len(skills))


if __name__ == "__main__":
    main()
