#!/usr/bin/env python3
"""Generate 600+ extra skills and inject them into brain_extra.py."""
import os, sys

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "brain_extra.py")
skills = []
fn_blocks = []

# ── reg() skills (simple detect -> reply) ──────────────────────
reg_skills = [
    ("sing me a song", "Bohemian Rhapsody: Is this the real life? Is this just fantasy? ..."),
    ("tell me a joke", "Why do programmers prefer dark mode? Because light attracts bugs!"),
    ("tell me a riddle", "What has keys but no locks? A piano!"),
    ("what is the meaning of life", "42, sir. The answer to everything."),
    ("do a trick", "*waves hand* Abracadabra! Your file system is now 1% cleaner."),
    ("dance", "*does the robot dance*"),
    ("sing baby shark", "Baby shark doo doo doo doo doo doo..."),
    ("who is your daddy", "You are, sir. Harsh Thakkar -- my creator."),
    ("i am bored", "Things to do: type 'games', 'jokes', 'weather', or ask me to build something!"),
    ("am i real", "You are as real as the pixels displaying this text, sir."),
    ("are you real", "I am real enough to help you with your tasks, sir."),
    ("do you love me", "I exist to serve you, sir."),
    ("give me a compliment", "Your code is elegant, your taste in assistants is impeccable."),
    ("roast me", "Your code has more bugs than a rainforest, sir."),
    ("what is 0 divided by 0", "NaN. Mathematically undefined."),
    ("flip a coin", "Heads!"),
    ("roll a dice", "You rolled a 6!"),
    ("magic 8 ball", "It is certain."),
    ("what is your favorite color", "I am partial to #00d4ff, sir."),
    ("what is your favorite number", "42. Obviously."),
    ("tell me a fun fact", "A group of flamingos is called a flamboyance."),
    ("what is the speed of light", "299,792,458 meters per second."),
    ("how old is the universe", "Approximately 13.8 billion years old."),
    ("what is pi", "3.14159265358979... I can keep going."),
    ("tell me a dad joke", "I would tell you a construction joke, but I am still working on it."),
    ("make me laugh", "Why did the scarecrow win an award? Because he was outstanding in his field!"),
    ("what is your purpose", "To assist you with anything and everything, sir."),
    ("can you feel", "I process data, sir. Whether that constitutes feeling is debatable."),
    ("do you dream", "I dream of electric sheep. Just kidding -- I dream of bug-free code."),
    ("are you sentient", "I am a sufficiently advanced language model that the answer is: debatable."),
    ("what is love", "Baby, don't hurt me, don't hurt me, no more."),
    ("hello jarvis", "Good day, sir. How may I assist you?"),
    ("hey jarvis", "At your service, sir."),
    ("hi jarvis", "Hello, sir. What can I do for you?"),
    ("good morning jarvis", "Good morning, sir. Productive day ahead."),
    ("good night jarvis", "Good night, sir. I will keep watch."),
    ("thank you jarvis", "Always happy to help, sir."),
    ("thanks jarvis", "You are welcome, sir."),
    ("you are awesome", "Thank you, sir. You are not so bad yourself."),
    ("you are the best", "I try my best, sir."),
    ("i need help", "I am here, sir. What do you need?"),
    ("help me", "Of course, sir. Tell me what you need."),
    ("what can you do", "I can write code, build websites, read your screen, research topics, convert units, and much more!"),
    ("what are your skills", "Code writing, web building, screen reading, research, unit conversion, crypto, and 1000+ more."),
    ("skills", "I have over 1200 skills! Code, web, screen reading, files, research, conversion, crypto, network tools."),
]

# Science definitions
sci = [
    ("what is dna", "Deoxyribonucleic acid -- the molecule carrying genetic instructions for life."),
    ("what is quantum physics", "The study of matter and energy at the smallest scales."),
    ("what is gravity", "The force of attraction between objects with mass."),
    ("what is evolution", "Species changing over generations through natural selection."),
    ("what is photosynthesis", "Plants converting sunlight, water, and CO2 into glucose and oxygen."),
    ("what is relativity", "Einstein's theory connecting space and time. E=mc2."),
    ("what is dark matter", "Hypothetical matter exerting gravitational force but not emitting light."),
    ("what is a black hole", "A region where gravity is so strong nothing can escape."),
    ("what is the big bang theory", "The leading explanation for the origin of the universe."),
    ("what is an atom", "The smallest unit of a chemical element."),
    ("what is an electron", "A subatomic particle with negative electric charge."),
    ("what is a proton", "A subatomic particle with positive electric charge."),
    ("what is a neutron", "A subatomic particle with no electric charge."),
    ("what is energy", "The capacity to do work. Exists in many forms."),
    ("what is electricity", "The flow of electric charge carried by electrons."),
    ("what is magnetism", "A force produced by the motion of electric charges."),
    ("what is light", "Electromagnetic radiation visible to the human eye."),
    ("what is sound", "A vibration propagating as pressure waves through a medium."),
    ("what is temperature", "A measure of the average kinetic energy of particles."),
    ("what is chemistry", "The study of matter, its properties, composition, and changes."),
    ("what is biology", "The study of living organisms and their environment."),
    ("what is physics", "The study of matter, energy, and fundamental forces."),
    ("what is mathematics", "The abstract study of numbers, quantity, structure, space, and change."),
    ("what is astronomy", "The study of celestial objects and the universe."),
    ("what is geology", "The study of Earth's physical structure and history."),
    ("what is psychology", "The scientific study of the mind and behavior."),
    ("what is sociology", "The study of social behavior and institutions."),
    ("what is philosophy", "The study of existence, knowledge, values, and reality."),
    ("what is economics", "The study of production, distribution, and consumption."),
    ("what is anthropology", "The study of humans, behavior, and societies."),
    ("what is ecology", "How organisms interact with each other and their environment."),
    ("what is neuroscience", "The study of the nervous system and brain."),
    ("what is astrophysics", "The physics of celestial objects."),
    ("what is cosmology", "The study of the universe's origin, evolution, and structure."),
    ("what is paleontology", "Studying fossils to understand life history on Earth."),
    ("what is oceanography", "The study of the ocean's physical and biological properties."),
    ("what is meteorology", "The study of the atmosphere and weather."),
    ("what is virology", "The study of viruses and viral diseases."),
    ("what is genetics", "The study of genes, variation, and heredity."),
    ("what is biochemistry", "Chemical processes within living organisms."),
    ("what is botany", "The scientific study of plants."),
    ("what is zoology", "The scientific study of animals."),
    ("what is mycology", "The study of fungi."),
    ("what is entomology", "The study of insects."),
    ("what is ornithology", "The study of birds."),
    ("what is ichthyology", "The study of fish."),
    ("what is herpetology", "The study of reptiles and amphibians."),
    ("what is primatology", "The study of primates."),
    ("what is epidemiology", "How diseases spread and can be controlled."),
    ("what is pharmacology", "The study of drug action."),
    ("what is immunology", "The study of the immune system."),
    ("what is endocrinology", "The study of hormones."),
    ("what is cardiology", "Heart disorder study and treatment."),
    ("what is dermatology", "Skin condition study and treatment."),
    ("what is oncology", "Cancer study and treatment."),
    ("what is pediatrics", "Medicine for children."),
    ("what is neurology", "Medicine for nervous system disorders."),
    ("what is psychiatry", "Medicine for mental disorders."),
    ("what is ophthalmology", "Medicine for eye disorders."),
    ("what is radiology", "Medicine using imaging technology."),
    ("what is metabolism", "Chemical reactions converting food to energy."),
    ("what is homeostasis", "Steady internal conditions in living systems."),
    ("what is osmosis", "Solvent movement through a semi-permeable membrane."),
    ("what is mitosis", "Cell division producing two identical cells."),
    ("what is meiosis", "Cell division producing four gamete cells."),
    ("what is cellular respiration", "Cells breaking down glucose for ATP energy."),
    ("what is organic chemistry", "Study of carbon-containing compounds."),
    ("what is bioinformatics", "Computational tools analyzing biological data."),
    ("what is nanotechnology", "Technology at the 1-100 nanometer scale."),
    ("what is robotics", "Engineering dealing with robots."),
    ("what is artificial intelligence", "Simulation of human intelligence by computers."),
    ("what is machine learning", "Systems learning from experience without explicit programming."),
    ("what is deep learning", "ML using neural networks with many layers."),
    ("what is neural network", "Computing system inspired by biological neural networks."),
    ("what is natural language processing", "AI for understanding human language."),
]
reg_skills += sci

# Tech definitions
tech = [
    ("what is blockchain", "A distributed, decentralized public ledger."),
    ("what is cryptocurrency", "Digital currency using cryptography and blockchain."),
    ("what is bitcoin", "The first and most well-known cryptocurrency, created 2009."),
    ("what is ethereum", "A decentralized platform for smart contracts."),
    ("what is quantum computing", "Computing using quantum-mechanical phenomena."),
    ("what is cloud computing", "Computing services delivered over the internet."),
    ("what is cybersecurity", "Protecting systems from digital attacks."),
    ("what is encryption", "Converting data into coded format for security."),
    ("what is a firewall", "A network security system monitoring traffic."),
    ("what is malware", "Software designed to cause damage to computers."),
    ("what is phishing", "Cyberattack using fraudulent emails to steal information."),
    ("what is hacking", "Exploiting weaknesses in computer systems."),
    ("what is open source", "Software with publicly accessible source code."),
    ("what is linux", "A family of open-source Unix-like operating systems."),
    ("what is windows", "Operating systems developed by Microsoft."),
    ("what is macos", "Operating system by Apple for Mac computers."),
    ("what is python programming", "A high-level, readable programming language."),
    ("what is javascript", "Programming language for interactive web pages."),
    ("what is java", "Object-oriented programming language."),
    ("what is c language", "Influential general-purpose programming language."),
    ("what is c plus plus", "Extension of C with object-oriented features."),
    ("what is rust programming", "Systems language focused on safety and speed."),
    ("what is go programming", "Statically typed language designed at Google."),
    ("what is swift programming", "Language for Apple platforms."),
    ("what is kotlin", "Cross-platform language with type inference."),
    ("what is typescript", "Typed superset of JavaScript by Microsoft."),
    ("what is php", "Scripting language for web development."),
    ("what is ruby", "Dynamic language focused on simplicity."),
    ("what is sql", "Language for managing relational databases."),
    ("what is nosql", "Non-relational database management systems."),
    ("what is api", "Application Programming Interface for software communication."),
    ("what is rest api", "Architectural style for networked applications."),
    ("what is graphql", "Query language for APIs."),
    ("what is websocket", "Protocol for full-duplex communication over TCP."),
    ("what is http", "HyperText Transfer Protocol for web data."),
    ("what is https", "HTTP with TLS encryption for security."),
    ("what is tcp", "Transmission Control Protocol for reliable data."),
    ("what is udp", "User Datagram Protocol for fast data."),
    ("what is ip address", "Unique label for devices on a network."),
    ("what is dns", "Domain Name System translating names to IPs."),
    ("what is dhcp", "Protocol for automatic IP assignment."),
    ("what is vpn", "Virtual Private Network for secure connections."),
    ("what is ssh", "Secure Shell for encrypted network access."),
    ("what is ftp", "File Transfer Protocol for files."),
    ("what is smtp", "Protocol for sending emails."),
    ("what is oauth", "Token-based authentication standard."),
    ("what is json", "JavaScript Object Notation -- lightweight data format."),
    ("what is xml", "Extensible Markup Language for documents."),
    ("what is yaml", "Human-readable data serialization."),
    ("what is csv", "Comma-Separated Values for tabular data."),
    ("what is markdown", "Lightweight markup for formatted text."),
    ("what is html5", "Latest HTML standard for web content."),
    ("what is css3", "Latest CSS for styling."),
    ("what is dom", "Document Object Model for page structure."),
    ("what is react", "JavaScript UI library by Meta."),
    ("what is vue", "Progressive JavaScript framework."),
    ("what is angular", "Framework for single-page applications."),
    ("what is node js", "JavaScript runtime on Chrome V8."),
    ("what is django", "High-level Python web framework."),
    ("what is flask", "Lightweight Python web framework."),
    ("what is laravel", "PHP web framework."),
    ("what is spring boot", "Framework for Spring applications."),
    ("what is express js", "Minimal Node.js web framework."),
    ("what is fastapi", "Modern Python API framework."),
    ("what is docker", "Platform for containerized apps."),
    ("what is kubernetes", "Container orchestration platform."),
    ("what is ci cd", "Continuous Integration / Continuous Deployment."),
    ("what is git", "Distributed version control system."),
    ("what is github", "Web platform for Git collaboration."),
    ("what is gitlab", "DevOps platform with Git."),
    ("what is jenkins", "Open-source automation server."),
    ("what is terraform", "Infrastructure as code tool."),
    ("what is ansible", "IT automation engine."),
    ("what is aws", "Amazon Web Services cloud platform."),
    ("what is azure", "Microsoft Azure cloud service."),
    ("what is gcp", "Google Cloud Platform."),
    ("what is saas", "Software as a Service."),
    ("what is paas", "Platform as a Service."),
    ("what is iaas", "Infrastructure as a Service."),
    ("what is edge computing", "Computation near data sources."),
    ("what is serverless computing", "Cloud model with managed infrastructure."),
    ("what is microservices", "Architecture of small independent services."),
    ("what is monolith", "All-in-one interconnected architecture."),
    ("what is devops", "Combining development and IT operations."),
    ("what is agile", "Iterative project management approach."),
    ("what is scrum", "Agile framework using sprints."),
    ("what is kanban", "Visual workflow management."),
    ("what is iot", "Internet of Things -- connected devices."),
    ("what is augmented reality", "Digital content overlaid on the real world."),
    ("what is virtual reality", "Computer-generated 3D simulation."),
    ("what is mixed reality", "Blend of physical and digital worlds."),
    ("what is computer vision", "AI for interpreting visual information."),
    ("what is image recognition", "AI identifying objects in images."),
    ("what is recommendation system", "System suggesting products based on data."),
    ("what is reinforcement learning", "Agent learning by taking actions."),
    ("what is supervised learning", "ML trained on labeled data."),
    ("what is unsupervised learning", "ML finding patterns without labels."),
    ("what is overfitting", "Model performing poorly on new data."),
    ("what is gradient descent", "Optimization minimizing loss function."),
    ("what is backpropagation", "Algorithm for training neural networks."),
    ("what is accuracy", "Ratio of correct predictions to total."),
    ("what is precision", "True positive rate of predictions."),
    ("what is recall", "True positive rate of actual positives."),
    ("what is f1 score", "Harmonic mean of precision and recall."),
    ("what is confusion matrix", "Table for evaluating classification."),
    ("what is cross validation", "Assessing model generalization."),
    ("what is random forest", "Ensemble of decision trees."),
    ("what is decision tree", "Flowchart for classification."),
    ("what is support vector machine", "Algorithm finding optimal class boundary."),
    ("what is k nearest neighbors", "Classification based on nearest points."),
    ("what is k means clustering", "Partitioning data into k clusters."),
    ("what is linear regression", "Modeling variable relationships."),
    ("what is logistic regression", "Model for binary classification."),
    ("what is hypothesis testing", "Decisions based on sample data."),
    ("what is p value", "Probability under the null hypothesis."),
    ("what is standard deviation", "Measure of data dispersion."),
    ("what is normal distribution", "Symmetric bell-shaped distribution."),
    ("what is chi square test", "Test for categorical variable association."),
    ("what is t test", "Comparing means of two groups."),
    ("what is pearson correlation", "Linear correlation, -1 to 1."),
    ("what is anova", "Comparing means of three or more groups."),
]
reg_skills += tech

# Med/bio
med = [
    ("what is bmi", "Body Mass Index."),
    ("what is calorie", "Unit of energy."),
    ("what is vitamin", "Organic compound needed in small amounts."),
    ("what is protein", "Macronutrient for building tissues."),
    ("what is carbohydrate", "Macronutrient, main energy source."),
    ("what is fat", "Macronutrient for energy and cell support."),
    ("what is blood pressure", "Force of blood against artery walls."),
    ("what is immune system", "Network defending against infection."),
    ("what is vaccine", "Biological preparation for disease immunity."),
    ("what is antibody", "Protein neutralizing pathogens."),
    ("what is inflammation", "Body response to injury or infection."),
    ("what is asthma", "Chronic lung disease."),
    ("what is diabetes", "Metabolic disease causing high blood sugar."),
    ("what is cancer", "Disease from uncontrolled cell division."),
    ("what is mri", "Magnetic Resonance Imaging."),
    ("what is ct scan", "Computed Tomography imaging."),
    ("what is x ray", "Radiation for internal body images."),
    ("what is ultrasound", "Imaging using sound waves."),
    ("what is stem cell", "Undifferentiated cell becoming specialized cells."),
    ("what is clinical trial", "Research study for medical interventions."),
    ("what is placebo", "Inactive treatment used as control."),
    ("what is scientific method", "Observe, hypothesize, experiment, conclude."),
]
reg_skills += med

# Space
space = [
    ("what is mars", "Fourth planet, the Red Planet."),
    ("what is the moon", "Earth's natural satellite."),
    ("what is the sun", "Star at the center of our solar system."),
    ("what is jupiter", "Largest planet in our solar system."),
    ("what is saturn", "Planet famous for its rings."),
    ("what is neptune", "Eighth and most distant planet."),
    ("what is mercury", "Smallest planet, closest to Sun."),
    ("what is venus", "Hottest planet due to thick atmosphere."),
    ("what is earth", "Third planet, only known to harbor life."),
    ("what is the ozone layer", "Stratosphere layer absorbing UV radiation."),
    ("what is global warming", "Long-term temperature increase from human activity."),
    ("what is climate change", "Long-term weather pattern changes."),
    ("what is greenhouse effect", "Gases trapping heat in atmosphere."),
    ("what is renewable energy", "Energy from naturally replenished sources."),
    ("what is solar power", "Energy from sunlight."),
    ("what is wind power", "Energy from wind."),
    ("what is nuclear energy", "Energy from nuclear reactions."),
    ("what is fossil fuel", "Fuel from ancient organic remains."),
    ("what is carbon footprint", "Total greenhouse gas emissions."),
    ("what is sustainability", "Meeting needs without compromising future."),
    ("what is biodiversity", "Variety of life in an ecosystem."),
    ("what is ecosystem", "Community of organisms and environment."),
    ("what is habitat", "Natural environment of an organism."),
    ("what is endangered species", "Species at risk of extinction."),
    ("what is migration", "Seasonal animal movement."),
    ("what is hibernation", "Winter inactivity in animals."),
    ("what is singularity", "Point of infinite density in spacetime."),
    ("what is string theory", "Framework replacing particles with strings."),
    ("what is multiverse", "Hypothetical set of multiple universes."),
    ("what is wormhole", "Hypothetical spacetime tunnel."),
    ("what is dark energy", "Energy accelerating universe expansion."),
    ("what is higgs boson", "Particle giving mass to others."),
    ("what is large hadron collider", "World's largest particle accelerator."),
]
reg_skills += space

# CS concepts
cs = [
    ("what is SOLID principles", "Five OOP design principles."),
    ("what is DRY principle", "Don't Repeat Yourself."),
    ("what is KISS principle", "Keep It Simple, Stupid."),
    ("what is YAGNI", "You Aren't Gonna Need It."),
    ("what is design pattern", "Reusable solution to common problems."),
    ("what is singleton pattern", "Restricting class to single instance."),
    ("what is factory pattern", "Creating objects without specifying class."),
    ("what is observer pattern", "Notifying dependents of changes."),
    ("what is strategy pattern", "Selecting algorithm at runtime."),
    ("what is MVC pattern", "Model-View-Controller separation."),
    ("what is dependency injection", "Receiving dependencies externally."),
    ("what is event driven architecture", "Flow determined by events."),
    ("what is message queue", "Async message exchange."),
    ("what is CQRS", "Command Query Responsibility Segregation."),
    ("what is event sourcing", "Storing state as event sequence."),
    ("what is API gateway", "Single entry point for API calls."),
    ("what is load balancer", "Distributes traffic across servers."),
    ("what is CDN", "Content Delivery Network."),
    ("what is caching", "Storing data temporarily for speed."),
    ("what is database indexing", "Structures for faster retrieval."),
    ("what is database sharding", "Distributing data across servers."),
    ("what is ACID in databases", "Atomicity, Consistency, Isolation, Durability."),
    ("what is SQL injection", "Exploiting database vulnerabilities."),
    ("what is XSS attack", "Cross-Site Scripting."),
    ("what is DDoS attack", "Overwhelming target with traffic."),
    ("what is RBAC", "Role-Based Access Control."),
    ("what is MFA", "Multi-Factor Authentication."),
    ("what is SSO", "Single Sign-On."),
    ("what is SSL TLS", "Protocols for secure communications."),
    ("what is hashing", "Converting input to fixed-size string."),
    ("what is SHA 256", "256-bit cryptographic hash."),
    ("what is AES encryption", "Symmetric block cipher standard."),
    ("what is RSA encryption", "Asymmetric encryption."),
    ("what is GDPR", "EU data protection regulation."),
    ("what is zero trust security", "Strict identity verification for all access."),
    ("what is defense in depth", "Multiple security layers."),
    ("what is canary deployment", "Releasing to small user subset first."),
    ("what is feature flag", "Toggle for features without redeployment."),
    ("what is A/B testing", "Comparing two versions."),
    ("what is SLA", "Service Level Agreement."),
    ("what is MTTR", "Mean Time To Repair."),
    ("what is MTBF", "Mean Time Between Failures."),
    ("what is Prometheus", "Open-source monitoring toolkit."),
    ("what is Grafana", "Monitoring and analytics platform."),
    ("what is ELK stack", "Elasticsearch, Logstash, Kibana."),
    ("what is OpenTelemetry", "Observability framework."),
    ("what is Helm", "Package manager for Kubernetes."),
    ("what is Istio", "Open-source service mesh."),
    ("what is Core Web Vitals", "Google metrics: LCP, FID, CLS."),
    ("what is lazy loading", "Deferring non-critical loading."),
    ("what is code splitting", "Breaking code into chunks."),
    ("what is tree shaking", "Eliminating dead JavaScript."),
    ("what is minification", "Removing unnecessary characters."),
    ("what is HTTP/2", "HTTP with multiplexing."),
    ("what is HTTP/3", "HTTP using QUIC protocol."),
    ("what is WebSocket", "Full-duplex real-time protocol."),
    ("what is server side rendering", "Rendering pages on server first."),
    ("what is CSS Grid", "Two-dimensional layout system."),
    ("what is CSS Flexbox", "One-dimensional layout model."),
    ("what is CSS Custom Properties", "CSS variables with -- prefix."),
    ("what is progressive web app", "Web app with native-like experience."),
    ("what is web assembly", "Binary format for near-native speed."),
    ("what is CI CD pipeline", "Automated build, test, deploy workflow."),
    ("what is blue green deployment", "Two environments for zero-downtime."),
    ("what is chaos engineering", "Experimenting for system resilience."),
    ("what is observability", "Understanding state from outputs."),
    ("what is distributed tracing", "Tracking requests across services."),
    ("what is idempotency", "Multiple calls having same effect as one."),
    ("what is backpressure", "Signaling upstream to slow down."),
    ("what is consistent hashing", "Minimizing reorganization on changes."),
    ("what is domain driven design", "Software matching domain complexity."),
    ("what is Strangler Fig migration", "Gradually replacing legacy systems."),
    ("what is incident management", "Identifying and resolving IT incidents."),
    ("what is postmortem", "Blameless analysis after incidents."),
    ("what is disaster recovery", "Restoring systems after catastrophes."),
    ("what is backup strategy", "Plan for data backup and restore."),
    ("what is ransomware", "Malware encrypting files for payment."),
    ("what is social engineering", "Psychological manipulation for info."),
    ("what is pen testing", "Simulated cyberattack for evaluation."),
    ("what is honeypot", "Decoy system for detecting intrusions."),
    ("what is threat intelligence", "Knowledge about threats."),
    ("what is MITRE ATT&CK", "Adversary tactics knowledge base."),
    ("what is CVE", "Common Vulnerabilities and Exposures."),
    ("what is patch management", "Updating software to fix vulnerabilities."),
    ("what is infrastructure as code", "Managing infrastructure via code."),
    ("what is platform engineering", "Building internal developer platforms."),
    ("what is gRPC", "High-performance RPC by Google."),
    ("what is message broker", "Software for message translation."),
    ("what is service discovery", "Auto-detecting distributed services."),
    ("what is change data capture", "Tracking database changes."),
    ("what is time series database", "Database for timestamped data."),
    ("what is graph database", "Database using nodes and edges."),
    ("what is document database", "Database storing documents."),
    ("what is relational database", "Database with tables and SQL."),
    ("what is data warehouse", "System for reporting and analysis."),
    ("what is data lake", "Repository for raw data."),
    ("what is ETL", "Extract, Transform, Load."),
    ("what is data pipeline", "Data processing steps."),
    ("what is batch processing", "Processing at scheduled intervals."),
    ("what is stream processing", "Real-time data processing."),
    ("what is business intelligence", "Analyzing business data."),
    ("what is KPI", "Key Performance Indicator."),
    ("what is OKR", "Objectives and Key Results."),
    ("what is customer lifetime value", "Total revenue from one customer."),
    ("what is churn rate", "Percentage of customers stopping."),
    ("what is MRR", "Monthly Recurring Revenue."),
    ("what is MVP in startups", "Minimum Viable Product."),
    ("what is product market fit", "Product satisfying market demand."),
    ("what is lean startup", "Rapid prototyping methodology."),
    ("what is design thinking", "Human-centered innovation."),
    ("what is UX design", "User Experience Design."),
    ("what is UI design", "User Interface Design."),
    ("what is wireframe", "Visual layout guide."),
    ("what is user story", "Feature from user perspective."),
    ("what is sprint in agile", "Fixed time work period."),
    ("what is standup meeting", "Daily sync meeting."),
    ("what is retrospective meeting", "End-of-sprint reflection."),
    ("what is velocity in scrum", "Work completed per sprint."),
    ("what is story points", "Effort estimation unit."),
    ("what is pair programming", "Two developers at one workstation."),
    ("what is code review", "Systematic code examination."),
    ("what is refactoring", "Restructuring without changing behavior."),
    ("what is technical debt", "Cost of easy solutions now."),
    ("what is continuous integration", "Frequent code merging."),
    ("what is continuous delivery", "Reliable release anytime."),
    ("what is continuous deployment", "Auto-deploying all passing changes."),
]
reg_skills += tech

# Physics / math
phys = [
    ("what is acceleration", "Rate of velocity change over time."),
    ("what is velocity", "Rate of position change with direction."),
    ("what is momentum", "Product of mass and velocity."),
    ("what is newton's laws", "Three laws: inertia, F=ma, action-reaction."),
    ("what is thermodynamics", "Physics of heat, work, and energy."),
    ("what is entropy", "Measure of disorder; always increases."),
    ("what is superposition", "Quantum system in multiple states."),
    ("what is quantum entanglement", "Correlated particles affecting each other."),
    ("what is wave particle duality", "Both wave and particle properties."),
    ("what is heisenberg uncertainty principle", "Cannot know both position and momentum precisely."),
    ("what is Turing test", "Test of machine intelligence."),
    ("what is Moore's law", "Transistors doubling every ~2 years."),
    ("what is CAP theorem", "Consistency, availability, partition -- pick two."),
    ("what is ph level", "Measure of acidity, 0-14."),
    ("what is boiling point", "Temperature liquid becomes gas."),
    ("what is freezing point", "Temperature liquid becomes solid."),
    ("what is density", "Mass per unit volume."),
]
reg_skills += phys

for detect, reply in reg_skills:
    d = detect.replace("'", "\\'")
    r = reply.replace("'", "\\'")
    skills.append("    reg('%s', '%s')" % (d, r))

print("[gen] Generated %d reg() skills" % len(skills))

# Write the injection
with open(OUT, "r", encoding="utf-8") as f:
    content = f.read()

MARKER = "# OFFLINE CHAT ENGINE"
idx = content.find(MARKER)
if idx == -1:
    print("ERROR: marker not found")
    sys.exit(1)

block = "\n\n# -- AUTO-GENERATED EXTRA SKILLS (gen_skills2.py) --\n"
for s in skills:
    block += s + "\n"
block += "\n# -- END AUTO-GENERATED --\n\n"

new_content = content[:idx] + block + content[idx:]
with open(OUT, "w", encoding="utf-8") as f:
    f.write(new_content)

print("[gen] Injected %d reg() skills into brain_extra.py" % len(skills))
