#!/usr/bin/env python3
"""Add more skills to brain_extra.py to reach 1000+ total."""
import os, sys

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "brain_extra.py")
skills = []

# More trivia, utilities, coding, math
more = [
    # Coding syntax help
    ("how to write a for loop python", "for i in range(10): print(i)"),
    ("how to write a while loop python", "while condition: # do something"),
    ("how to define a function python", "def my_function(param1, param2): return result"),
    ("how to create a class python", "class MyClass: def __init__(self): self.x = 0"),
    ("how to make a list python", "my_list = [1, 2, 3, 4, 5]"),
    ("how to make a dictionary python", "my_dict = {'key': 'value'}"),
    ("how to read a file python", "with open('file.txt', 'r') as f: data = f.read()"),
    ("how to write a file python", "with open('file.txt', 'w') as f: f.write('hello')"),
    ("how to import in python", "import module_name OR from module import function"),
    ("how to handle exceptions python", "try: # code except Exception as e: print(e)"),
    ("how to use list comprehension python", "[x**2 for x in range(10)]"),
    ("how to sort a list python", "my_list.sort() or sorted(my_list)"),
    ("how to reverse a list python", "my_list.reverse() or my_list[::-1]"),
    ("how to join a list python", "' '.join(my_list)"),
    ("how to split a string python", "my_string.split('delimiter')"),
    ("how to strip whitespace python", "my_string.strip()"),
    ("how to format a string python", "f'Hello {name}' or 'Hello {}'.format(name)"),
    ("how to check if key in dictionary python", "'key' in my_dict"),
    ("how to merge dictionaries python", "{**dict1, **dict2} or dict1 | dict2"),
    ("how to use enumerate python", "for i, val in enumerate(my_list): print(i, val)"),
    ("how to use zip python", "for a, b in zip(list1, list2): print(a, b)"),
    ("how to use map python", "result = map(function, iterable)"),
    ("how to use filter python", "result = filter(function, iterable)"),
    ("how to use lambda python", "square = lambda x: x**2"),
    ("how to use decorators python", "@decorator def function(): pass"),
    ("how to create virtual environment python", "python -m venv myenv && source myenv/bin/activate"),
    ("how to install packages python", "pip install package_name"),
    ("how to create requirements file python", "pip freeze > requirements.txt"),
    ("how to run python script", "python script.py"),
    ("how to check python version", "python --version"),
    ("how to use os module python", "import os; os.listdir(), os.path.exists()"),
    ("how to use json module python", "import json; json.loads(), json.dumps()"),
    ("how to use re module python", "import re; re.search(), re.findall()"),
    ("how to use datetime python", "from datetime import datetime; datetime.now()"),
    ("how to use random python", "import random; random.randint(1,10)"),
    ("how to use requests python", "import requests; r = requests.get(url)"),
    ("how to use sqlite3 python", "import sqlite3; conn = sqlite3.connect('db.sqlite')"),
    ("how to use subprocess python", "import subprocess; subprocess.run(['ls'])"),
    ("how to use argparse python", "import argparse; parser = argparse.ArgumentParser()"),
    ("how to create a flask app python", "from flask import Flask; app = Flask(__name__)"),
    ("how to create a fastapi app python", "from fastapi import FastAPI; app = FastAPI()"),
    ("how to create a django project python", "django-admin startproject myproject"),
    ("how to create a tkinter window python", "import tkinter as tk; root = tk.Tk()"),
    ("how to create a gui python", "import tkinter as tk; app = tk.Tk(); app.mainloop()"),
    ("how to make a python executable", "pip install pyinstaller && pyinstaller --onefile script.py"),
    ("how to make a python package", "Create __init__.py, setup.py, and package structure"),
    ("how to use numpy python", "import numpy as np; arr = np.array([1,2,3])"),
    ("how to use pandas python", "import pandas as pd; df = pd.DataFrame({'a': [1,2]})"),
    ("how to use matplotlib python", "import matplotlib.pyplot as plt; plt.plot([1,2,3])"),
    ("how to use seaborn python", "import seaborn as sns; sns.barplot(data=df)"),
    ("how to use scikit learn python", "from sklearn.model_selection import train_test_split"),
    ("how to use tensorflow python", "import tensorflow as tf; model = tf.keras.Sequential()"),
    ("how to use pytorch python", "import torch; tensor = torch.tensor([1,2,3])"),
    ("how to usebeautifulsoup python", "from bs4 import BeautifulSoup; soup = BeautifulSoup(html)"),
    ("how to scrape a website python", "import requests; from bs4 import BeautifulSoup"),
    ("how to send email python", "import smtplib; server = smtplib.SMTP('smtp.gmail.com', 587)"),
    ("how to create api python", "from fastapi import FastAPI; app = FastAPI()"),
    ("how to use websocket python", "import websocket; ws = websocket.WebSocketApp(url)"),
    ("how to use threading python", "import threading; t = threading.Thread(target=func)"),
    ("how to use multiprocessing python", "from multiprocessing import Process; p = Process(target=func)"),
    ("how to use asyncio python", "import asyncio; async def main(): await func()"),
    ("how to use queue python", "from queue import Queue; q = Queue(); q.put(item)"),
    ("how to use collections python", "from collections import Counter, defaultdict, deque"),
    ("how to use itertools python", "import itertools; for item in itertools.chain(a, b)"),
    ("how to use functools python", "from functools import lru_cache; @lru_cache"),
    ("how to use pathlib python", "from pathlib import Path; p = Path('.')"),
    ("how to use logging python", "import logging; logging.basicConfig(level=logging.INFO)"),
    ("how to use pytest python", "def test_example(): assert 1+1 == 2"),
    ("how to use unittest python", "import unittest; class Test(unittest.TestCase):"),
    ("how to use dataclasses python", "from dataclasses import dataclass; @dataclass"),
    ("how to use typing python", "from typing import List, Dict, Optional"),
    ("how to use enum python", "from enum import Enum; class Color(Enum): RED=1"),
    ("how to use abc python", "from abc import ABC, abstractmethod"),
    ("how to use context manager python", "class Ctx: def __enter__(self): ... def __exit__(self, *a): ..."),
    ("how to use generator python", "def gen(): yield value"),
    ("how to use iterator python", "class Iter: def __iter__(self): ... def __next__(self): ..."),
    ("how to use property python", "@property def name(self): return self._name"),
    ("how to use staticmethod python", "@staticmethod def func(): ..."),
    ("how to use classmethod python", "@classmethod def from_string(cls, s): ..."),
    ("how to use slots python", "class MyClass: __slots__ = ['x', 'y']"),
    ("how to use metaclass python", "class Meta(type): pass"),
    ("how to use exec python", "exec('print(1)')"),
    ("how to use eval python", "eval('1+1')"),
    ("how to use pickle python", "import pickle; pickle.dump(obj, file); pickle.load(file)"),
    ("how to use shelve python", "import shelve; d = shelve.open('mydb'); d['key'] = val"),
    ("how to use sqlite python", "import sqlite3; conn = sqlite3.connect('db.sqlite')"),
    ("how to use csv module python", "import csv; reader = csv.reader(open('file.csv'))"),
    ("how to use xml python", "import xml.etree.ElementTree as ET"),
    ("how to use html python", "import html; html.escape(), html.unescape()"),
    ("how to use hashlib python", "import hashlib; hashlib.sha256(data).hexdigest()"),
    ("how to use hmac python", "import hmac; hmac.new(key, msg, hashlib.sha256).hexdigest()"),
    ("how to use secrets python", "import secrets; token = secrets.token_hex(16)"),
    ("how to use base64 python", "import base64; base64.b64encode(data)"),
    ("how to use uuid python", "import uuid; u = uuid.uuid4()"),
    ("how to use socket python", "import socket; s = socket.socket()"),
    ("how to use http server python", "python -m http.server 8000"),
    ("how to use ssl python", "import ssl; ctx = ssl.create_default_context()"),
    ("how to use ftplib python", "from ftplib import FTP; ftp = FTP()"),
    ("how to use imaplib python", "import imaplib; mail = imaplib.IMAP4_SSL('imap.gmail.com')"),
    ("how to use poplib python", "import poplib; mail = poplib.POP3_SSL('pop.gmail.com')"),
    ("how to use smtplib python", "import smtplib; server = smtplib.SMTP_SSL('smtp.gmail.com', 465)"),
    ("how to use urllib python", "from urllib.request import urlopen; resp = urlopen(url)"),
    ("how to use email python", "from email.mime.text import MIMEText"),
    ("how to use calendar python", "import calendar; calendar.month(2024, 1)"),
    ("how to use timeit python", "import timeit; timeit.timeit('sum(range(100))')"),
    ("how to use cProfile python", "import cProfile; cProfile.run('my_function()')"),
    ("how to use pdb python", "import pdb; pdb.set_trace()"),
    ("how to use trace python", "import trace; tracer = trace.Trace()"),
    ("how to use dis python", "import dis; dis.dis(my_function)"),
    ("how to use inspect python", "import inspect; inspect.getsource(func)"),
    ("how to use keyword python", "import keyword; keyword.iskeyword('class')"),
    ("how to use token python", "import token; token.tok_name[token.NUMBER]"),
    ("how to use ast python", "import ast; tree = ast.parse(code)"),
    ("how to use compile python", "code = compile(source, filename, 'exec')"),
    ("how to use importlib python", "import importlib; mod = importlib.import_module('os')"),
    ("how to use pkgutil python", "import pkgutil; list(pkgutil.iter_modules())"),
    ("how to use sys module python", "import sys; sys.argv, sys.path, sys.version"),
    ("how to use os path python", "import os.path; os.path.join(), os.path.exists()"),
    ("how to use shutil python", "import shutil; shutil.copy(), shutil.move()"),
    ("how to use glob python", "import glob; glob.glob('*.py')"),
    ("how to use fnmatch python", "import fnmatch; fnmatch.fnmatch('test.py', '*.py')"),
    ("how to use tempfile python", "import tempfile; f = tempfile.NamedTemporaryFile()"),
    ("how to use gzip python", "import gzip; f = gzip.open('file.gz', 'wb')"),
    ("how to use zipfile python", "import zipfile; z = zipfile.ZipFile('archive.zip')"),
    ("how to use tarfile python", "import tarfile; t = tarfile.open('archive.tar.gz')"),
    ("how to use zlib python", "import zlib; compressed = zlib.compress(data)"),
    ("how to use bz2 python", "import bz2; compressed = bz2.compress(data)"),
    ("how to use lzma python", "import lzma; compressed = lzma.compress(data)"),
    ("how to use struct python", "import struct; struct.pack('i', 42)"),
    ("how to use ctypes python", "import ctypes; libc = ctypes.CDLL('libc.so.6')"),
    ("how to use mmap python", "import mmap; f = mmap.mmap(fileno, length)"),
    ("how to use signal python", "import signal; signal.signal(signal.SIGINT, handler)"),
    ("how to use threading lock python", "import threading; lock = threading.Lock()"),
    ("how to use concurrent futures python", "from concurrent.futures import ThreadPoolExecutor"),
    ("how to usemultiprocessing pool python", "from multiprocessing import Pool; Pool(4).map(func, items)"),
    ("how to use array module python", "import array; arr = array.array('i', [1,2,3])"),
    ("how to use bisect python", "import bisect; bisect.insort(sorted_list, value)"),
    ("how to use heapq python", "import heapq; heapq.nlargest(3, iterable)"),
    ("how to use queue module python", "from queue import Queue; q = Queue(); q.put(item)"),
    ("how to use copy module python", "import copy; deep = copy.deepcopy(obj)"),
    ("how to use pprint python", "from pprint import pprint; pprint(data)"),
    ("how to use textwrap python", "import textwrap; textwrap.fill(text, 70)"),
    ("how to use difflib python", "import difflib; difflib.unified_diff(a, b)"),
    ("how to use decimal python", "from decimal import Decimal; Decimal('0.1') + Decimal('0.2')"),
    ("how to use fractions python", "from fractions import Fraction; Fraction(1, 3)"),
    ("how to use statistics python", "import statistics; statistics.mean([1,2,3])"),
    ("how to use math module python", "import math; math.sqrt(16), math.pi"),
    ("how to use cmath python", "import cmath; cmath.sqrt(-1)"),
    ("how to use statistics mean python", "import statistics; statistics.mean(data)"),
    ("how to use statistics median python", "import statistics; statistics.median(data)"),
    ("how to use statistics stdev python", "import statistics; statistics.stdev(data)"),
    ("how to use statistics variance python", "import statistics; statistics.variance(data)"),
    ("how to use statistics mode python", "import statistics; statistics.mode(data)"),
    ("how to use statistics harmonic mean python", "import statistics; statistics.harmonic_mean(data)"),
    ("how to use statistics geometric mean python", "import statistics; statistics.geometric_mean(data)"),
    ("how to use statistics quantiles python", "import statistics; statistics.quantiles(data)"),
    ("how to use statistics normaldist python", "from statistics import NormalDist; nd = NormalDist()"),
    ("how to use random choices python", "import random; random.choices(population, k=3)"),
    ("how to use random shuffle python", "import random; random.shuffle(my_list)"),
    ("how to use random sample python", "import random; random.sample(population, k=2)"),
    ("how to use random seed python", "import random; random.seed(42)"),
    ("how to use random uniform python", "import random; random.uniform(1.0, 10.0)"),
    ("how to use random gauss python", "import random; random.gauss(mu=0, sigma=1)"),
    ("how to use random expovariate python", "import random; random.expovariate(1.0)"),
    ("how to use random triangular python", "import random; random.triangular(0, 10)"),
    ("how to use random randrange python", "import random; random.randrange(0, 100, 5)"),
    ("how to use random bytes python", "import random; random.randbytes(16)"),
    # More trivia / fun
    ("what is the largest ocean", "The Pacific Ocean, covering about 165 million sq km."),
    ("what is the tallest mountain", "Mount Everest at 8,849 meters above sea level."),
    ("what is the longest river", "The Nile River at approximately 6,650 km."),
    ("what is the largest desert", "The Sahara Desert at about 9.2 million sq km."),
    ("what is the deepest ocean trench", "The Mariana Trench at 10,994 meters deep."),
    ("what is the largest animal", "The blue whale, up to 30 meters long."),
    ("what is the fastest animal", "The peregrine falcon at over 390 km/h in a dive."),
    ("what is the smallest country", "Vatican City at 0.44 sq km."),
    ("what is the most spoken language", "Mandarin Chinese by native speakers, English by total speakers."),
    ("what is the most populous country", "India with over 1.4 billion people."),
    ("what is the largest planet", "Jupiter, with a mass 318 times Earth."),
    ("what is the hottest planet", "Venus at about 465 degrees Celsius."),
    ("what is the coldest planet", "Neptune at about -214 degrees Celsius."),
    ("what is the largest star", "UY Scuti, about 1,700 times the Sun's radius."),
    ("what is the closest star", "The Sun at about 150 million km away."),
    ("what is the fastest human", "Usain Bolt at 44.72 km/h (27.8 mph)."),
    ("what is the largest organ", "The skin, covering about 2 square meters."),
    ("what is the hardest substance", "Diamond, rating 10 on the Mohs scale."),
    ("what is the most abundant gas in atmosphere", "Nitrogen at about 78% of the atmosphere."),
    ("what is the most abundant element in universe", "Hydrogen at about 75% of ordinary matter."),
    ("what is the speed of sound", "About 343 meters per second in air at 20 degrees C."),
    ("what is absolute zero", "-273.15 degrees Celsius, the lowest possible temperature."),
    ("what is pi day", "March 14th (3/14), matching the first digits of pi."),
    ("what is eulers number", "Euler's number e is approximately 2.71828."),
    ("what is avogadro's number", "6.022 x 10^23, the number of particles in one mole."),
    ("what is planck's constant", "6.626 x 10^-34 joule-seconds."),
    ("what is boltzmann constant", "1.381 x 10^-23 joules per kelvin."),
    ("what is the golden ratio", "Approximately 1.618, often denoted by the Greek letter phi."),
    ("what is the fibonacci sequence", "0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89..."),
    ("what is the riemann hypothesis", "A conjecture about the zeros of the Riemann zeta function."),
    ("what is P vs NP", "A major unsolved problem: can every problem whose solution is quickly verified be quickly solved?"),
    ("what is the halting problem", "Determining whether a program will finish running or run forever -- proven undecidable."),
    ("what is Gödel's incompleteness theorem", "Any consistent formal system contains statements that are true but unprovable."),
    ("what is chaos theory", "Sensitive dependence on initial conditions in dynamic systems."),
    ("what is fractal", "A pattern that repeats at every scale, like a Mandelbrot set."),
    ("what is the butterfly effect", "Small changes in initial conditions leading to large differences in outcomes."),
    ("what is information entropy", "A measure of uncertainty in information, developed by Shannon."),
    ("what is shannon entropy", "H = -sum(p * log2(p)), measuring information content."),
    ("what is Kolmogorov complexity", "The shortest description of a string by a program."),
    ("what is NP complete", "The hardest problems in NP, where any NP problem can be reduced to them."),
    ("what is quicksort", "A divide-and-conquer sorting algorithm with O(n log n) average."),
    ("what is merge sort", "A stable, divide-and-conquer sorting algorithm."),
    ("what is binary search", "Finding an element in a sorted array in O(log n) time."),
    ("what is hash table", "A data structure mapping keys to values using a hash function."),
    ("what is linked list", "A linear data structure where elements are not stored contiguously."),
    ("what is stack data structure", "LIFO -- Last In, First Out data structure."),
    ("what is queue data structure", "FIFO -- First In, First Out data structure."),
    ("what is heap data structure", "A complete binary tree where parent is greater/less than children."),
    ("what is graph data structure", "A set of nodes connected by edges."),
    ("what is breadth first search", "Exploring all neighbors at current depth before moving deeper."),
    ("what is depth first search", "Exploring as far as possible along each branch before backtracking."),
    ("what is dynamic programming", "Breaking problems into overlapping subproblems and storing solutions."),
    ("what is greedy algorithm", "Making locally optimal choices at each step."),
    ("what is divide and conquer", "Recursively breaking a problem into smaller subproblems."),
    ("what is backtracking", "Trying all possibilities and undoing choices that fail."),
    ("what is bit manipulation", "Operations on individual bits: AND, OR, XOR, shifts."),
    ("what is two pointer technique", "Using two pointers moving toward each other or in same direction."),
    ("what is sliding window", "A window moving across data to find subarray/substring."),
    ("what is topological sort", "Ordering vertices in a directed acyclic graph."),
    ("what is Dijkstra algorithm", "Finding shortest paths from a source in a weighted graph."),
    ("what is bellman ford algorithm", "Shortest paths allowing negative edge weights."),
    ("what is Floyd Warshall algorithm", "All-pairs shortest paths in a weighted graph."),
    ("what is minimum spanning tree", "A subset of edges connecting all vertices with minimum total weight."),
    ("what is Prim algorithm", "Growing MST one vertex at a time."),
    ("what is Kruskal algorithm", "Growing MST by adding cheapest edges that don't create cycles."),
    ("what is Union Find", "A data structure tracking disjoint sets with path compression."),
    ("what is trie data structure", "A tree for storing strings, used in autocomplete and spell-checking."),
    ("what is AVL tree", "A self-balancing binary search tree."),
    ("what is red black tree", "A self-balancing binary search tree with color properties."),
    ("what is B tree", "A self-balancing tree for databases and file systems."),
    ("what is segment tree", "A tree for querying ranges of an array."),
    ("what is Fenwick tree", "A binary indexed tree for prefix sums."),
    ("what is suffix array", "A sorted array of all suffixes of a string."),
    ("what is LRU cache", "Least Recently Used cache evicting oldest access."),
    ("what is bloom filter", "A probabilistic data structure for set membership testing."),
    ("what is skip list", "A probabilistic alternative to balanced trees."),
    ("what is circular buffer", "A fixed-size buffer wrapping around on itself."),
    ("what is doubly linked list", "A linked list where each node has pointers to next and previous."),
    ("what is circular linked list", "A linked list where the last node points back to the first."),
    ("what is adjacency matrix", "A 2D array representing graph edges."),
    ("what is adjacency list", "A list of lists representing graph edges."),
    ("what is directed graph", "A graph where edges have direction."),
    ("what is undirected graph", "A graph where edges have no direction."),
    ("what is weighted graph", "A graph where edges have associated values."),
    ("what is DAG", "Directed Acyclic Graph -- no cycles, used in scheduling."),
    ("what is complete graph", "A graph where every pair of vertices is connected."),
    ("what is bipartite graph", "A graph whose vertices can be divided into two disjoint sets."),
    ("what is Euler path", "A path visiting every edge exactly once."),
    ("what is Hamiltonian path", "A path visiting every vertex exactly once."),
    ("what is planar graph", "A graph that can be drawn without edge crossings."),
    ("what is graph coloring", "Assigning colors to vertices so no adjacent vertices share color."),
    ("what is max flow min cut", "The maximum flow equals the minimum cut capacity."),
    ("what is Ford Fulkerson algorithm", "Finding maximum flow in a flow network."),
    ("what is network flow", "The rate of material flow through a network."),
    ("what is matching in graph", "A set of edges without common vertices."),
    ("what is maximum matching", "The largest possible matching in a graph."),
]

for detect, reply in more:
    d = detect.replace("'", "\\'")
    r = reply.replace("'", "\\'")
    skills.append("    reg('%s', '%s')" % (d, r))

print("[gen] Generated %d more reg() skills" % len(skills))

# Inject
with open(OUT, "r", encoding="utf-8") as f:
    content = f.read()

MARKER = "# -- END AUTO-GENERATED --"
idx = content.find(MARKER)
if idx == -1:
    print("ERROR: end marker not found")
    sys.exit(1)

block = ""
for s in skills:
    block += s + "\n"

new_content = content[:idx] + block + content[idx:]
with open(OUT, "w", encoding="utf-8") as f:
    f.write(new_content)

print("[gen] Injected %d more skills. Total should be 1000+." % len(skills))
